/* ============================================================
   NurtureFlow — Internationalization (i18n)
   Français 🇫🇷 | العربية 🇸🇦 | English 🇬🇧
   ============================================================ */

const LANGS = {
  fr: { label: 'Français', flag: '🇫🇷', dir: 'ltr' },
  ar: { label: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  en: { label: 'English', flag: '🇬🇧', dir: 'ltr' }
};

let currentLang = localStorage.getItem('nf_lang') || 'fr';

// ── Translation dictionaries ──
const translations = {

// ═══════════════════════════════════════
//  FRENCH
// ═══════════════════════════════════════
fr: {
  // App
  app_name: 'NurtureFlow',
  app_tagline: 'من الحياة الزوجية إلى الأبوة',

  // Auth
  auth_email: 'Email',
  auth_password: 'كلمة المرور',
  auth_login: 'Se connecter',
  auth_no_account: 'ليس لديك حساب؟',
  auth_create_account: 'إنشاء حساب للزوجين',
  auth_create_title: 'إنشاء حسابكم كزوجين',
  auth_partner1: 'PARTENAIRE 1',
  auth_partner2: 'PARTENAIRE 2',
  auth_couple_info: 'INFORMATIONS COUPLE',
  auth_security: 'الأمان',
  auth_firstname: 'الاسم الأول',
  auth_age: 'العمر',
  auth_woman: 'Femme',
  auth_man: 'Homme',
  auth_marriage_duration: 'مدة الزواج (مثال: 3 سنوات)',
  auth_baby_age: 'عمر الطفل (مثال: 4 أشهر)',
  auth_password_min: 'كلمة المرور (4 أحرف على الأقل)',
  auth_password_confirm: 'تأكيد كلمة المرور',
  auth_create_btn: 'إنشاء الحساب',
  auth_fill_all: 'يرجى ملء جميع الحقول',
  auth_pwd_mismatch: 'كلمتا المرور غير متطابقتين',
  auth_required: 'الاسم والبريد وكلمة المرور مطلوبة',

  // Navigation
  nav_home: 'Home',
  nav_results: 'النتائج',
  nav_library: 'المكتبة',
  nav_profile: 'Profil',

  // Drawer
  drawer_home: 'Accueil',
  drawer_evaluations: 'التقييمات',
  drawer_plan: 'خطة مخصصة',
  drawer_checkup: 'Couple Check-Up',
  drawer_daily: 'Suivi quotidien',
  drawer_alerts: 'Alertes',
  drawer_sage_femme: 'Assistant Sage-Femme',
  drawer_library: 'المكتبة',
  drawer_settings: 'الإعدادات',
  drawer_admin: 'Admin Dashboard',
  drawer_new_couple: 'Nouveau Couple',
  drawer_logout: 'تسجيل الخروج',
  drawer_welcome: 'مرحباً',
  drawer_couple_since: 'Couple depuis',

  // Home
  home_hello: 'مرحباً',
  home_ready: 'مستعدة للمرافقة؟',
  home_global_progress: 'Progression globale',
  home_evals_completed: 'تقييمات مكتملة',
  home_tip_of_day: 'نصيحة اليوم',
  home_tip_title: 'الحفاظ على الرابط العاطفي',
  home_tip_desc: 'الطقوس اليومية الصغيرة تقوّي رابطكما.',
  home_evaluations: 'التقييم الذاتي',
  home_psycho: 'نفسي',
  home_conjugal: 'Conjugale',
  home_sexual: 'Sexuelle',
  home_first_eval: 'أول تقييم',
  home_first_eval_desc: 'ابدئي تقييمك الأول لاكتشاف ملفك.',
  home_last_eval: 'آخر تقييم',
  home_daily_tracking: 'Suivi Quotidien',
  home_midwife: 'Sage-Femme',
  home_score: 'Score',

  // Questionnaire
  q_previous: 'السابق',
  q_next: 'Suivant',
  q_finish: 'Terminer',
  q_question: 'سؤال',
  q_never: 'أبداً',
  q_rarely: 'Rarement',
  q_sometimes: 'Parfois',
  q_often: 'Souvent',
  q_always: 'دائماً',

  // Questionnaire titles
  qt_psycho: 'الصحة النفسية',
  qt_conjugal: 'Relation Conjugale',
  qt_sexual: 'Vie Intime Post-Partum',

  // Questionnaire questions — Psycho
  qp1: 'كيف تقيّمين مستوى التوتر لديك هذا الأسبوع؟',
  qp1h: 'فكري في لحظات التوتر أو القلق.',
  qp2: 'هل شعرتِ بتعب مفرط في الأيام الأخيرة؟',
  qp2h: 'التعب الجسدي و/أو النفسي المرتبط بالأمومة.',
  qp3: 'كيف تصفين مزاجك العام؟',
  qp3h: 'فكري في حالتك العاطفية العامة.',
  qp4: 'هل تشعرين بالقلق تجاه مسؤوليات الأمومة؟',
  qp4h: 'القلق المرتبط بدورك كأم.',
  qp5: 'هل تستطيعين التكيف مع التغييرات منذ قدوم المولود؟',
  qp5h: 'قدرتك على إدارة الروتين الجديد.',
  qp6: 'هل مررتِ بلحظات إحباط؟',
  qp6h: 'الشعور بعدم القدرة على المواصلة.',
  qp7: 'هل تخصصين وقتاً لنفسك؟',
  qp7h: 'لحظات استرخاء، ترفيه، راحة.',
  qp8: 'هل تنامين بما يكفي لتشعري بالراحة؟',
  qp8h: 'جودة ومدة نومك.',
  qp9: 'هل تشعرين بالسيطرة على يومك؟',
  qp9h: 'الشعور بالتحكم في حياتك.',
  qp10: 'هل تشعرين بالدعم العاطفي؟',
  qp10h: 'Soutien famille, amis, partenaire.',

  // Questionnaire questions — Conjugal
  qc1: 'كيف تقيّمين تواصلك مع شريكك؟',
  qc1h: 'تواصلكما خلال الأيام السبعة الأخيرة.',
  qc2: 'هل تشعرين بدعم شريكك؟',
  qc2h: 'الدعم العملي والعاطفي.',
  qc3: 'هل عشتِ خلافات أو نزاعات؟',
  qc3h: 'Tensions, disputes, malentendus.',
  qc4: 'هل أنتِ راضية عن علاقتكما الزوجية؟',
  qc4h: 'Satisfaction globale.',
  qc5: 'هل قضيتما وقتاً ممتعاً معاً؟',
  qc5h: 'لحظات مشتركة بدون التزامات الأبوة.',
  qc6: 'هل تتقاسمان مهام الأبوة بالتساوي؟',
  qc6h: 'توزيع الرعاية والمهام.',
  qc7: 'هل تعبّرين عن احتياجاتك بسهولة؟',
  qc7h: 'Communication ouverte sur vos attentes.',
  qc8: 'هل تشعرين بأن شريكك يستمع إليك؟',
  qc8h: 'الاهتمام والتفهم.',
  qc9: 'هل شاركتما لحظات فرح معاً؟',
  qc9h: 'التواطؤ والسعادة المشتركة.',
  qc10: 'هل تشعرين بالتناغم مع شريكك؟',
  qc10h: 'الارتباط والتوحد.',

  // Questionnaire questions — Sexual
  qs1: 'هل تشعرين بالرغبة تجاه شريكك؟',
  qs1h: 'الانجذاب والرغبة في الحميمية.',
  qs2: 'هل أنتِ راضية عن حياتكما الحميمية الحالية؟',
  qs2h: 'Niveau de satisfaction.',
  qs3: 'هل تتحدثان بصراحة عن حياتكما الجنسية؟',
  qs3h: 'القدرة على طرح الموضوع.',
  qs4: 'هل واجهتِ صعوبات جسدية؟',
  qs4h: 'Douleurs, inconfort, changements.',
  qs5: 'هل تشعرين بالخوف أو الألم؟',
  qs5h: 'مخاوف مرتبطة بالاستئناف.',
  qs6: 'هل تشعرين بالارتياح مع جسمك؟',
  qs6h: 'Image corporelle post-partum.',
  qs7: 'هل كانت لديكما لحظات حميمية غير جنسية؟',
  qs7h: 'أحضان، ملامسات، حنان.',
  qs8: 'هل يؤثر التعب على حياتكما الحميمية؟',
  qs8h: 'تأثير الإرهاق.',
  qs9: 'هل ناقشتما موضوع منع الحمل؟',
  qs9h: 'التواصل حول الوقاية.',
  qs10: 'هل تشعرين بأنك مرغوبة؟',
  qs10h: 'الشعور بالجاذبية.',

  // Results
  res_global: 'Global',
  res_global_index: 'مؤشر التوازن العام',
  res_analysis: 'تحليل مفصّل',
  res_psycho: 'نفسي',
  res_conjugal: 'Conjugal',
  res_sexual: 'Sexuel',
  res_explanation: 'شرح مخصص',
  res_first_eval_msg: 'أكملي تقييماتك الأولى لتحليل مخصص.',
  res_excellent: 'Excellent',
  res_bon: 'Bon',
  res_moyen: 'Moyen',
  res_faible: 'Faible',
  res_orientation: 'التوجيه المُوصى به',
  res_consult: 'Score {types} faible. Consultez un professionnel.',

  // Library
  lib_title: 'المكتبة',
  lib_subtitle: 'نصائح الخبراء لكل مرحلة.',
  lib_search: 'Rechercher un article...',
  lib_timeline: 'TIMELINE POST-PARTUM',
  lib_all: 'الكل',
  lib_mental_health: 'الصحة النفسية',
  lib_sexuality: 'الحياة الجنسية',
  lib_couple_life: 'Vie de Couple',
  lib_breastfeeding: 'Allaitement',
  lib_featured: 'Article Vedette',
  lib_postpartum_title: 'ما بعد الولادة مباشرة',
  lib_postpartum_desc: 'فهم تغييرات الـ48 ساعة الأولى.',
  lib_read_more: 'اقرأي المزيد →',
  lib_breathing: 'التنفس بعد الولادة',
  lib_sleep: 'إدارة قلة النوم',
  lib_communication: 'التواصل بين الزوجين',
  lib_comm_desc: 'الحفاظ على الرابط بعد قدوم المولود.',
  lib_partner_role: 'دور الشريك',
  lib_intimacy: 'استعادة الحميمية',
  lib_content_period: 'CONTENU',
  lib_months: 'MOIS',

  // Profile
  prof_info: 'INFORMATIONS',
  prof_age: 'العمر',
  prof_sex: 'Sexe',
  prof_marriage: 'مدة الزواج',
  prof_baby: 'عمر الطفل',
  prof_partner2: 'Partenaire 2',
  prof_not_set: 'غير محدد',
  prof_stats: 'الإحصائيات',
  prof_evaluations: 'التقييمات',
  prof_articles: 'مقالات',
  prof_streak: 'أيام المتابعة',
  prof_settings: 'الإعدادات',
  prof_notif: 'Notifications',
  prof_lang: 'Langue',
  prof_version: 'Version',

  // Sage-femme
  sf_title: 'Assistant Sage-Femme',
  sf_subtitle: 'Conseils professionnels post-partum',
  sf_all: 'الكل',
  sf_postpartum: 'Post-partum',
  sf_breastfeeding: 'Allaitement',
  sf_contraception: 'Contraception',
  sf_sexuality: 'الحياة الجنسية',
  sf_alerts: '⚠️ Alertes',

  // Sage-femme tips
  sft1_title: 'التعافي بعد الولادة',
  sft1_text: 'الأسابيع الأولى حاسمة. امنحي نفسك الراحة واستمعي لجسمك. النزيف بعد الولادة يدوم 4 إلى 6 أسابيع. استشيري الطبيب إذا ظهرت حمى أو آلام شديدة.',
  sft2_title: 'Allaitement maternel',
  sft2_text: 'الإرضاع في الساعة الأولى. أرضعي حسب الطلب. إذا شعرتِ بألم، تحققي من وضعية الإرضاع. اطلبي مساعدة مستشارة الرضاعة.',
  sft3_title: 'Contraception post-partum',
  sft3_text: 'يمكن البدء من اليوم 21. الخيارات: اللولب، حبوب البروجسترون، الغرسة. الرضاعة الحصرية ليست وسيلة منع حمل موثوقة.',
  sft4_title: 'استئناف العلاقة الجنسية',
  sft4_text: 'لا يوجد موعد إلزامي. الجفاف المهبلي طبيعي. استخدمي مزلقاً مائياً. تواصلي مع شريكك.',
  sft5_title: 'Signes d\'alerte ⚠️',
  sft5_text: 'استشيري فوراً إذا: حمى >38°C، نزيف شديد، ألم حاد، حزن >أسبوعين، أفكار مظلمة، صعوبة في التعلق بالطفل.',
  sft6_title: 'كآبة ما بعد الولادة مقابل الاكتئاب',
  sft6_text: 'كآبة الولادة (ي3-ي10): طبيعية ومؤقتة. اكتئاب ما بعد الولادة (>أسبوعين): حزن عميق وفقدان الاهتمام. تحدثي مع مختص.',
  sft7_title: 'Engorgement mammaire',
  sft7_text: 'شائع في ي3-ي5. كمادات دافئة قبل الرضاعة وباردة بعدها. تدليك تحت الدوش. أرضعي بشكل متكرر.',
  sft8_title: 'إعادة تأهيل العجان',
  sft8_text: 'مُوصى بها بعد كل ولادة، من الأسبوع 6-8. تمنع سلس البول وتحسن الراحة الحميمية.',

  // Daily tracking
  daily_title: 'كيف تشعرين اليوم؟',
  daily_subtitle: 'سجّلي مزاجك اليومي.',
  daily_mood: 'مزاج اليوم',
  daily_exhausted: 'منهك',
  daily_sad: 'Triste',
  daily_neutral: 'Neutre',
  daily_good: 'بخير',
  daily_great: 'Super',
  daily_stress: 'Niveau de stress',
  daily_conjugal: 'Satisfaction conjugale',
  daily_intimate: 'Satisfaction intime',
  daily_save: 'Enregistrer mon suivi',
  daily_saved: 'تم الحفظ!',
  daily_evolution: 'التطور الأخير',
  daily_satisfaction: 'Satisfaction',
  daily_stress_label: 'Stress',
  daily_history: 'السجل الأخير',
  daily_no_entries: 'لا توجد إدخالات. ابدئي المتابعة أعلاه!',

  // Plan
  plan_title: 'خطة مخصصة',
  plan_subtitle: 'تمارين ونصائح حسب نتائجك',
  plan_days: 'أيام',
  plan_focus: 'Axes prioritaires',
  plan_focus_desc: 'بناءً على نتائجك، ننصح بالتركيز على:',
  plan_activities: 'الأنشطة',
  plan_completed: 'أنشطة مكتملة',
  plan_psycho_focus: 'الراحة النفسية',
  plan_comm_focus: 'communication conjugale',
  plan_pp_focus: 'accompagnement post-partum',

  // Check-up
  checkup_monthly: 'BILAN MENSUEL',
  checkup_global_score: 'Score Global',
  checkup_by_dimension: 'النتائج حسب البُعد',
  checkup_evolution: 'تطور النتائج',
  checkup_recommendations: 'RECOMMANDATIONS',
  checkup_start_plan: 'بدء خطة مخصصة',
  checkup_see_results: 'عرض النتائج المفصّلة',
  checkup_trend_up: '↑ En hausse',
  checkup_trend_down: '↓ En baisse',
  checkup_trend_stable: '= Stable',
  checkup_trend_new: 'Nouveau',

  // Alerts
  alerts_title: 'Alertes & Orientation',
  alerts_subtitle: 'متابعة ذكية لصحتك',
  alerts_all_good: 'كل شيء على ما يرام! ✨',
  alerts_none: 'لا توجد تنبيهات حالياً. واصلي المتابعة المنتظمة.',
  alerts_back_home: 'العودة إلى الرئيسية',
  alerts_important: 'Rappel important',
  alerts_disclaimer: 'NurtureFlow أداة وقائية وتوعوية. في حالة الضيق، اتصلي فوراً بأخصائي صحي.',
  alerts_alert: 'alerte',
  alerts_alerts: 'alertes',
  alerts_critical: 'حرج',
  alerts_criticals: 'حرجة',
  alerts_warning: 'avertissement',
  alerts_warnings: 'avertissements',

  // Admin
  admin_title: 'Administration NurtureFlow',
  admin_subtitle: 'Vue d\'ensemble de la plateforme',
  admin_dashboard: 'TABLEAU DE BORD',
  admin_couples: 'الأزواج المسجلون',
  admin_active: 'Actifs (7j)',
  admin_evals: 'التقييمات',
  admin_daily: 'Suivis quotidiens',
  admin_avg_scores: 'Scores Moyens Globaux',
  admin_score_distrib: 'توزيع النتائج',
  admin_evals_by_type: 'التقييمات حسب النوع',
  admin_recent_couples: 'الأزواج الأخيرون',
  admin_restricted: 'وصول محدود',
  admin_restricted_msg: 'هذا القسم مخصص للمسؤول فقط.',
  admin_info: 'INFORMATIONS',
  admin_return: 'Retour',

  // New couple
  nc_title: 'إنشاء زوجين جديدين',
  nc_subtitle: 'تسجيل زوجين في القاعدة',
  nc_create: 'إنشاء الزوجين',
  nc_creating: 'جاري الإنشاء...',
  nc_success: 'تم إنشاء الزوجين بنجاح!',
  nc_created: 'تم الإنشاء!',

  // Misc
  misc_just_now: 'À l\'instant',
  misc_ago_min: 'Il y a {n} min',
  misc_ago_hours: 'Il y a {n}h',
  misc_yesterday: 'Hier',
  misc_ago_days: 'Il y a {n} jours',
  misc_loading: 'Chargement...',
  misc_error: 'Erreur',
  misc_back: 'Retour',
  misc_min_read: 'min de lecture',
  misc_period: 'Période',
  misc_back_library: 'Retour à la bibliothèque',
  misc_video: 'Vidéo',
  misc_guide: 'Guide',
  misc_article: 'Article',

  // Results HTML static
  res_global: 'Global',
  res_analysis: 'Analyse Détaillée',
  res_explanation: 'Explication personnalisée',
  res_psychologique: 'Psychologique',
  res_conjugal: 'Conjugal',
  res_sexuel: 'Sexuel',

  // Library
  lib_months_unit: 'mois',

  // Splash
  splash_tagline: 'De la conjugalité à la parentalité',

  // Register placeholders (hardcoded)
  auth_marriage_placeholder: 'Durée du mariage (ex: 3 ans)',
  auth_baby_placeholder: 'Âge du bébé (ex: 4 mois)',

  // Error messages
  err_fill_all: 'Veuillez remplir tous les champs',
  err_pwd_mismatch: 'Les mots de passe ne correspondent pas',
  err_required: 'Prénom, email et mot de passe sont obligatoires',
  err_server: 'Erreur serveur',

  // Home
  home_evals_text: '{n}/3 évaluations complétées',
  home_last_eval_title: 'Dernière Évaluation',
  home_first_eval_title: 'Première Évaluation',
  home_first_eval_text: 'Commencez votre première évaluation pour découvrir votre profil de couple.',
  home_score_label: 'Score',
  home_new_modules: 'NOUVEAUX MODULES',
  home_weeks: 'Semaines S1-S12',
  home_journal: 'Journal de Bord',
  home_scales: 'Échelles Cliniques',
  home_tunisian: 'Coin Tunisien',

  // Results explanations
  res_transition: 'Votre relation traverse cette phase de transition ',
  res_resilience: 'avec une grande résilience. ',
  res_positive: 'de manière positive. ',
  res_challenges: 'avec quelques défis à relever. ',
  res_excellent_psycho: 'Excellent bien-être psychologique ({score}%). ',
  res_low_psycho: 'Votre bien-être psychologique ({score}%) nécessite une attention particulière. ',
  res_low_conjugal: 'La dimension conjugale ({score}%) pourrait être renforcée. ',
  res_low_sexual: 'La dimension intime ({score}%) mérite un accompagnement. ',
  res_first_eval_long: 'Complétez vos premières évaluations pour recevoir une analyse personnalisée.',
  res_orientation_title: 'Orientation recommandée',
  res_orientation_text: 'Score {types} faible. Consultez un professionnel.',

  // New Couple
  nc_partner1: 'PARTENAIRE 1',
  nc_partner2: 'PARTENAIRE 2',
  nc_couple_info: 'INFORMATIONS COUPLE',
  nc_security: 'SÉCURITÉ',
  nc_firstname: 'Prénom',
  nc_email: 'Email',
  nc_age: 'Âge',
  nc_woman: 'Femme',
  nc_man: 'Homme',

  // Suivi
  daily_days_dim: 'Dim',
  daily_days_lun: 'Lun',
  daily_days_mar: 'Mar',
  daily_days_mer: 'Mer',
  daily_days_jeu: 'Jeu',
  daily_days_ven: 'Ven',
  daily_days_sam: 'Sam',
  daily_conj_label: 'Conj',

  // Plan
  plan_loading_error: 'Erreur de chargement du plan.',
  plan_focus_psycho: 'bien-être psychologique',
  plan_focus_comm: 'communication conjugale',
  plan_focus_pp: 'accompagnement post-partum',

  // Checkup
  checkup_generating: 'جاري إنشاء التقرير...',
  checkup_psycho: 'نفسي',
  checkup_conjugal: 'Conjugal',
  checkup_sexual: 'Sexuel',
  checkup_no_data: 'أكملي تقييماً واحداً على الأقل لإنشاء تقريرك.',

  // Alerts
  alerts_loading_error: 'خطأ في تحميل التنبيهات.',

  // Admin
  admin_age_p1: 'عمر ش1',
  admin_sex_p1: 'Sexe P1',
  admin_age_p2: 'عمر ش2',
  admin_sex_p2: 'Sexe P2',
  admin_marriage: 'Mariage',
  admin_baby_age: 'عمر الطفل',
  admin_no_eval: 'لا يوجد تقييم',
  admin_no_daily: 'Aucun suivi',
  admin_loading_error: 'Erreur de chargement.',
  admin_evals_count: 'التقييمات ({n})',
  admin_daily_count: 'SUIVI QUOTIDIEN ({n})',
  admin_psycho: 'Psycho',

  // Timeline article
  timeline_article_not_found: 'المقال غير موجود.',
  timeline_read_time: '{n} min de lecture',
  timeline_period: 'الفترة {period} أشهر',

  // Semaines
  sem_title: 'Semaines Post-Partum',
  sem_week: 'SEMAINE',
  sem_medical: 'المتابعة الطبية',
  sem_maman: 'للأم',
  sem_couple: 'للزوجين',
  sem_bebe: 'رسالة المولود',
  sem_solutions: 'حلول عملية',
  sem_prev: '← السابق',
  sem_next: 'Suivant →',
  sem_week_of: 'Semaine {n} sur 12',

  // Journal
  journal_title: 'دفتر اليوميات',
  journal_expression: 'Espace d\'Expression',
  journal_expression_desc: 'مساحة آمنة للتعبير عن مشاعركم بصدق ومحبة.',
  journal_our_journal: 'دفتر يومياتنا',
  journal_live: 'تحديث مباشر',
  journal_maman: '♀ Maman',
  journal_partner: '♂ Partenaire',
  journal_today_feel: 'اليوم أشعر بـ:',
  journal_need: 'CE DONT J\'AI BESOIN :',
  journal_need_placeholder: 'مثال: قليل من النوم، حضن دافئ...',
  journal_sweet: 'كلمة حلوة لشريكي:',
  journal_sweet_placeholder: 'مثال: شكراً على رضعة الليلة...',
  journal_save: 'حفظ حالتي',
  journal_saved_notes: 'ملاحظات الأسبوع المحفوظة:',
  journal_no_notes: 'لا توجد ملاحظات حالياً. عبّري عن مشاعرك أعلاه.',
  journal_need_label: 'Besoin',
  journal_select_mood: 'اختاري مزاجك!',

  // Échelles
  scales_title: 'المقاييس السريرية',
  scales_tools: 'أدوات التقييم السريري',
  scales_measure: 'قياس لمرافقة أفضل',
  scales_desc: 'استبيانات PISQ-12 (الجنسية) ومقياس RAS (الرضا الزوجي) تساعدكم على تقييم حميميتكم.',
  scales_current_score: 'نتيجتك الحالية',
  scales_out_of: 'من {max} (تمت الإجابة: {answered}/{total})',
  scales_diag: 'التشخيص والنصائح:',
  scales_low: '⚠️ SCORE FAIBLE',
  scales_moderate: '⚡ نتيجة متوسطة',
  scales_good: '✅ BON SCORE',
  scales_excellent: '🌟 EXCELLENT SCORE',
  scales_pisq12_title: '❤ مقياس PISQ-12',
  scales_pisq12_sub: '(الجنسية)',
  scales_ras_title: '🤝 مقياس RAS',
  scales_ras_sub: '(Satisfaction)',
  scales_pisq12_q_title: 'استبيان PISQ-12: الجنسية بعد الولادة',
  scales_ras_q_title: 'استبيان RAS: الرضا الزوجي',
  scales_instruction: 'اختاري التردد الذي يناسب وضعك الحالي.',
  scales_calculate: 'حساب وتحليل',
  scales_reset: 'إعادة تعيين الاختبار',
  scales_privacy: 'احترام الخصوصية:',
  scales_privacy_text: 'لا تُرسل أي بيانات إلى خادم. تُحسب النتائج محلياً لضمان سرية بياناتك.',
  scales_never: 'أبداً',
  scales_rarely: 'نادراً',
  scales_sometimes: 'أحياناً',
  scales_frequently: 'غالباً',
  scales_always: 'دائماً',
  scales_all_answered: 'تمت الإجابة على جميع الأسئلة',
  scales_remaining: 'يتبقى {n} أسئلة بدون إجابة',
  scales_partial_warning: 'لم تتم الإجابة على جميع الأسئلة. النتيجة جزئية.',

  // Tounsi
  tounsi_title: 'Coin Tunisien',
  tounsi_wisdom: 'SAGESSE DE CHEZ NOUS',
  tounsi_main_title: 'زاوية الراحة "بالتونسي"',
  tounsi_main_desc: 'الجمع بين الدقة الطبية للقابلة التونسية ودفء تقاليدنا الغذائية والروحية.',
  tounsi_paroles_title: 'كلمات دافئة',
  tounsi_paroles_ar: 'كلام دافي',
  tounsi_generator: 'مولّد الراحة',
  tounsi_generator_desc: 'التعب يثقل على الزوجين؟ اضغطي لتوليد كلمة حنونة بالتونسي تهمسينها لشريكك.',
  tounsi_generate_btn: 'توليد كلمة جديدة',
  tounsi_nefsa_title: 'حمية النفاسة',
  tounsi_nefsa_sub: 'دعم الحليب والطاقة',
  tounsi_articles: 'مقالات الراحة',
  tounsi_footer: '© 2026 NurtureFlow — من الحياة الزوجية إلى الأبوة.',
  tounsi_footer_sub: 'صُمم للإرشاد والدعم وتشجيع الحوار. لا يغني عن استشارة القابلة أو الطبيب.',

  // Profile static
  prof_notifications: 'Notifications',
  prof_lang_display: 'اللغة: العربية',
  prof_ans: 'ans',

  // Drawer extra
  drawer_weeks: 'Semaines S1-S12',
  drawer_journal: 'دفتر اليوميات',
  drawer_scales: 'المقاييس السريرية',
  drawer_tunisian: 'Coin Tunisien',

  // Breastfeeding module
  bf_module_title: 'دليل الرضاعة الشامل',
  bf_module_desc: 'دليل شامل، اختبار، خرافات ويوميات',
  bf_title: 'الرضاعة الطبيعية',
  bf_subtitle: 'دليل شامل للأم المرضعة',
  bf_tab_guide: 'الدليل',
  bf_tab_myths: 'خرافات',
  bf_tab_quiz: 'اختبار',
  bf_tab_log: 'يوميات',
  bf_chapter: 'الفصل',
  bf_myths_title: 'خرافات وحقائق عن الرضاعة',
  bf_myths_desc: 'اضغطي على كل بطاقة لاكتشاف الحقيقة',
  bf_myth: 'خرافة',
  bf_reality: 'حقيقة',
  bf_quiz_title: 'اختبار تقييم الرضاعة',
  bf_quiz_desc: 'أجيبي على 18 سؤال لتقييم جودة الرضاعة',
  bf_yes: 'نعم',
  bf_no: 'لا',
  bf_quiz_excellent: 'الرضاعة تسير بشكل ممتاز',
  bf_quiz_good: 'صعوبات بسيطة',
  bf_quiz_attention: 'يوصى بالاستشارة',
  bf_quiz_urgent: 'تقييم مهني عاجل',
  bf_quiz_medical_alert: 'تنبيه طبي',
  bf_quiz_retry: 'إعادة الاختبار',
  bf_log_title: 'يوميات الرضاعة',
  bf_log_today: 'تسجيل اليوم',
  bf_log_feeds: 'عدد الرضعات',
  bf_log_duration: 'مدة الرضعة',
  bf_log_pumped: 'كمية الحليب المشفوط',
  bf_log_mood: 'حالتك المزاجية',
  bf_log_notes_placeholder: 'ملاحظات شخصية...',
  bf_log_save: 'حفظ',
  bf_log_saved: 'تم الحفظ!',
  bf_log_weekly: 'إحصائيات الأسبوع',
  bf_log_avg_feeds: 'معدل الرضعات',
  bf_log_days: 'أيام مسجلة',
  bf_log_pumped_total: 'مشفوط',
  bf_log_history: 'السجل',
  bf_log_feeds_short: 'رضعات',
  bf_log_empty: 'لا توجد تسجيلات بعد. ابدأي التسجيل أعلاه!',

  // Sexuality module
  sx_module_title: 'الحياة الجنسية والعناية بعد الولادة',
  sx_module_desc: 'دليل الجنسية بعد الولادة وعناية الخياطة',
  sx_title: 'الحياة الجنسية بعد الولادة',
  sx_subtitle: 'نصائح وإرشادات مهنية',
  sx_tab_guide: 'الدليل',
  sx_tab_myths: 'خرافات',
  sx_tab_consult: 'استشارة',
  sx_myths_title: 'خرافات وحقائق',
  sx_myths_desc: 'اضغطي على كل بطاقة لاكتشاف الحقيقة',
  sx_when_consult: 'متى يجب استشارة الطبيب؟',
  sx_consult_intro: 'يُنصح باستشارة أخصائية التوليد أو الطبيب إذا وُجد:',
  sx_consult_msg: 'لا تترددي في استشارة أخصائية التوليد أو طبيبك للحصول على المساعدة اللازمة.',

  // Medical alerts
  alert_bf_fever_title: 'حرارة أكثر من 38 درجة',
  alert_bf_fever_msg: 'إذا ترافق احتقان الثدي مع حرارة أكثر من 38 درجة يجب استشارة مختص فوراً.',
  alert_bf_redness_title: 'احمرار شديد بالثدي',
  alert_bf_redness_msg: 'احمرار متزايد أو تورم شديد بالثدي قد يشير إلى التهاب. يُنصح بالتواصل مع أخصائية توليد.',
  alert_bf_lump_title: 'كتلة مؤلمة بالثدي',
  alert_bf_lump_msg: 'وجود كتلة مؤلمة بالثدي يستوجب تقييماً طبياً عاجلاً.',
  alert_bf_refuse_title: 'رفض الطفل للرضاعة',
  alert_bf_refuse_msg: 'إذا رفض الطفل الرضاعة بشكل مستمر يُنصح باستشارة مختص.',
  alert_bf_weight_title: 'نقص وزن الطفل',
  alert_bf_weight_msg: 'نقص وزن الطفل أو عدم زيادته بشكل طبيعي قد يتطلب تقييم الرضاعة.',
  alert_epis_title: 'علامات خطر بشق العجان',
  alert_epis_msg: 'احمرار متزايد، إفرازات ذات رائحة كريهة، حرارة > 38°C، انفتاح الجرح — استشيري الطبيب فوراً.',
  alert_sx_pain_title: 'ألم مستمر أثناء العلاقة',
  alert_sx_pain_msg: 'الألم المستمر أثناء العلاقة الجنسية يحتاج استشارة مختص.',
  alert_ppd_title: 'اكتئاب ما بعد الولادة',
  alert_ppd_msg: 'حزن عميق أو فقدان الاهتمام لأكثر من أسبوعين يحتاج متابعة مختص.',
  alert_action_bf: 'فتح دليل الرضاعة',
  alert_action_sx: 'فتح دليل العناية',
  alert_action_eval: 'بدء التقييم',
  alerts_medical_intro: 'تنبيهات طبية مهمة يجب الانتباه إليها. استشيري المختص في حال ظهور أي من هذه العلامات.',

  // Newborn module
  nb_module_title: 'العناية بالمولود الجديد',
  nb_module_desc: 'دليل شامل للعناية بالمولود',
  nb_title: 'المولود الجديد',
  nb_subtitle: 'دليل العناية بالمولود',
  nb_tab_guide: 'الدليل',
  nb_tab_myths: 'خرافات',
  nb_myths_title: 'خرافات وحقائق عن المولود',
  nb_myths_desc: 'اضغطي على كل بطاقة لاكتشاف الحقيقة',

  // Myths module
  my_module_title: 'خرافات وحقائق',
  my_module_desc: 'جميع الخرافات الشائعة مع التصحيح العلمي',
  my_title: 'خرافات وحقائق',
  my_subtitle: '20 خرافة شائعة مع الحقيقة العلمية',
  my_tap_hint: 'اضغطي على أي بطاقة لاكتشاف الحقيقة',
  my_footer: 'المعلومات مبنية على توصيات منظمة الصحة العالمية والممارسات السريرية.',

  // Baby Age Widget
  baby_title: 'عمر المولود',
  baby_enter_info: 'أدخلي تاريخ وساعة الولادة',
  baby_date: 'تاريخ الولادة',
  baby_time: 'ساعة الولادة',
  baby_save: 'حفظ',
  baby_age_title: 'عمر طفلك',
  baby_months: 'شهر',
  baby_days: 'يوم',
  baby_hours: 'ساعة',
  baby_minutes: 'دقيقة',
  baby_newborn_msg: 'مبروك! طفلك حديث الولادة ❤️',
  baby_weeks_old: 'عمر الطفل: {n} أسابيع',

  // Notifications
  notif_title: 'Notifications',
  notif_clear: 'Tout effacer',
  notif_empty: 'Aucune notification pour le moment.',
  notif_just_now: 'À l\'instant',
  notif_min_ago: 'min',
  notif_hrs_ago: 'h',
  notif_days_ago: 'j',
  notif_welcome: 'Bienvenue sur NurtureFlow ! 🌸 Votre espace couple vous attend.',
  notif_eval_reminder: 'N\'oubliez pas de remplir votre évaluation hebdomadaire ! 📋',
  notif_baby_born: 'Félicitations pour la naissance de votre bébé ! 🎉',
  notif_baby_1week: 'Votre bébé a 1 semaine ! Les premiers jours sont précieux. 🎊',
  notif_baby_2weeks: 'Bébé a 2 semaines ! Pensez au suivi post-natal. 🌟',
  notif_baby_1month: 'Joyeux 1 mois à votre bébé ! 🎂',
  notif_baby_2months: 'Votre bébé a 2 mois ! Premier vaccin à prévoir. 🌸',
  notif_baby_3months: 'Félicitations, 3 mois déjà ! Un trimestre de bonheur. 🎈',
  notif_tip_water: 'Pensez à bien vous hydrater aujourd\'hui ! L\'allaitement augmente les besoins en eau.',
  notif_tip_breathe: 'Accordez-vous 5 minutes de respiration profonde. Votre bien-être compte.',
  notif_tip_hug: 'Un câlin de 20 secondes libère de l\'ocytocine. Prenez votre partenaire dans vos bras !',
  notif_tip_sleep: 'Dormez quand bébé dort. Le sommeil est votre meilleur allié.',
  notif_tip_breastfeed: 'Position confortable pour l\'allaitement : dos soutenu, coussins sous les bras.',
  notif_tip_walk: 'Une petite promenade de 15 min améliore l\'humeur et renforce le lien avec bébé.',
  notif_tip_talk: 'Prenez 10 minutes pour discuter avec votre partenaire. La communication renforce le couple.',
},

// ═══════════════════════════════════════
//  ARABIC
// ═══════════════════════════════════════
ar: {
  app_name: 'NurtureFlow',
  app_tagline: 'من الحياة الزوجية إلى الأبوة',

  auth_email: 'البريد الإلكتروني',
  auth_password: 'كلمة المرور',
  auth_login: 'تسجيل الدخول',
  auth_no_account: 'ليس لديك حساب؟',
  auth_create_account: 'إنشاء حساب للزوجين',
  auth_create_title: 'إنشاء حسابكم كزوجين',
  auth_partner1: 'الشريك 1',
  auth_partner2: 'الشريك 2',
  auth_couple_info: 'معلومات الزوجين',
  auth_security: 'الأمان',
  auth_firstname: 'الاسم الأول',
  auth_age: 'العمر',
  auth_woman: 'أنثى',
  auth_man: 'ذكر',
  auth_marriage_duration: 'مدة الزواج (مثال: 3 سنوات)',
  auth_baby_age: 'عمر الطفل (مثال: 4 أشهر)',
  auth_password_min: 'كلمة المرور (4 أحرف على الأقل)',
  auth_password_confirm: 'تأكيد كلمة المرور',
  auth_create_btn: 'إنشاء الحساب',
  auth_fill_all: 'يرجى ملء جميع الحقول',
  auth_pwd_mismatch: 'كلمتا المرور غير متطابقتين',
  auth_required: 'الاسم والبريد وكلمة المرور مطلوبة',

  nav_home: 'الرئيسية',
  nav_results: 'النتائج',
  nav_library: 'المكتبة',
  nav_profile: 'الملف',

  drawer_home: 'الرئيسية',
  drawer_evaluations: 'التقييمات',
  drawer_plan: 'خطة مخصصة',
  drawer_checkup: 'فحص الزوجين',
  drawer_daily: 'المتابعة اليومية',
  drawer_alerts: 'التنبيهات',
  drawer_sage_femme: 'مساعدة القابلة',
  drawer_library: 'المكتبة',
  drawer_settings: 'الإعدادات',
  drawer_admin: 'لوحة الإدارة',
  drawer_new_couple: 'زوجان جديدان',
  drawer_logout: 'تسجيل الخروج',
  drawer_welcome: 'مرحباً',
  drawer_couple_since: 'متزوجان منذ',

  home_hello: 'مرحباً',
  home_ready: 'هل أنتِ مستعدة للمرافقة؟',
  home_global_progress: 'التقدم العام',
  home_evals_completed: 'تقييمات مكتملة',
  home_tip_of_day: 'نصيحة اليوم',
  home_tip_title: 'الحفاظ على الترابط العاطفي',
  home_tip_desc: 'الطقوس اليومية الصغيرة تقوي رابطكم.',
  home_evaluations: 'التقييمات الذاتية',
  home_psycho: 'نفسي',
  home_conjugal: 'زوجي',
  home_sexual: 'جنسي',
  home_first_eval: 'التقييم الأول',
  home_first_eval_desc: 'ابدأي تقييمك الأول لاكتشاف ملفك الشخصي.',
  home_last_eval: 'آخر تقييم',
  home_daily_tracking: 'المتابعة اليومية',
  home_midwife: 'القابلة',
  home_score: 'النتيجة',

  q_previous: 'السابق',
  q_next: 'التالي',
  q_finish: 'إنهاء',
  q_question: 'السؤال',
  q_never: 'أبداً',
  q_rarely: 'نادراً',
  q_sometimes: 'أحياناً',
  q_often: 'غالباً',
  q_always: 'دائماً',

  qt_psycho: 'الرفاه النفسي',
  qt_conjugal: 'العلاقة الزوجية',
  qt_sexual: 'الحياة الحميمية بعد الولادة',

  qp1: 'كيف تقيّمين مستوى التوتر لديك هذا الأسبوع؟',
  qp1h: 'فكّري في لحظات التوتر والقلق.',
  qp2: 'هل شعرتِ بإرهاق شديد في الأيام الأخيرة؟',
  qp2h: 'إرهاق جسدي و/أو نفسي مرتبط بالأمومة.',
  qp3: 'كيف تصفين مزاجك العام؟',
  qp3h: 'فكّري في حالتك العاطفية الشاملة.',
  qp4: 'هل تشعرين بالقلق تجاه مسؤوليات الأمومة؟',
  qp4h: 'القلق المتعلق بدورك كأم.',
  qp5: 'هل تستطيعين التأقلم مع التغييرات منذ وصول الطفل؟',
  qp5h: 'قدرتك على إدارة الروتين الجديد.',
  qp6: 'هل مررتِ بلحظات إحباط؟',
  qp6h: 'الشعور بعدم القدرة على التحمل.',
  qp7: 'هل تخصصين وقتاً لنفسك؟',
  qp7h: 'لحظات الراحة والترفيه.',
  qp8: 'هل تنامين بما يكفي لتشعري بالراحة؟',
  qp8h: 'جودة ومدة نومك.',
  qp9: 'هل تشعرين بالسيطرة على حياتك اليومية؟',
  qp9h: 'الشعور بالتحكم في حياتك.',
  qp10: 'هل تشعرين بالدعم العاطفي؟',
  qp10h: 'دعم العائلة والأصدقاء والشريك.',

  qc1: 'كيف تقيّمين تواصلك مع شريكك؟',
  qc1h: 'حواراتكم خلال الأيام السبعة الأخيرة.',
  qc2: 'هل تشعرين بدعم شريكك لك؟',
  qc2h: 'الدعم العملي والعاطفي.',
  qc3: 'هل مررتم بنزاعات أو خلافات؟',
  qc3h: 'توترات، نقاشات، سوء تفاهم.',
  qc4: 'هل أنتِ راضية عن علاقتكما كزوجين؟',
  qc4h: 'الرضا العام.',
  qc5: 'هل قضيتما وقتاً نوعياً معاً؟',
  qc5h: 'لحظات مشتركة بدون واجبات الأبوة.',
  qc6: 'هل تتقاسمون المهام الأبوية بالتساوي؟',
  qc6h: 'توزيع الرعاية والمهام.',
  qc7: 'هل تعبّرين بسهولة عن احتياجاتك؟',
  qc7h: 'التواصل المفتوح حول توقعاتك.',
  qc8: 'هل تشعرين أن شريكك يستمع إليك؟',
  qc8h: 'الاهتمام والتفهم.',
  qc9: 'هل شاركتما لحظات فرح معاً؟',
  qc9h: 'التواطؤ والسعادة المشتركة.',
  qc10: 'هل تشعرين بالتواطؤ مع شريكك؟',
  qc10h: 'الترابط والوحدة.',

  qs1: 'هل تشعرين بالرغبة تجاه شريكك؟',
  qs1h: 'الانجذاب والرغبة في العلاقة الحميمية.',
  qs2: 'هل أنتِ راضية عن حياتكم الحميمية الحالية؟',
  qs2h: 'مستوى الرضا.',
  qs3: 'هل تتحدثون بصراحة عن حياتكم الجنسية؟',
  qs3h: 'القدرة على طرح الموضوع.',
  qs4: 'هل واجهتِ صعوبات جسدية؟',
  qs4h: 'آلام، عدم راحة، تغيرات.',
  qs5: 'هل تشعرين بالتخوف أو الألم؟',
  qs5h: 'مخاوف مرتبطة بالعودة.',
  qs6: 'هل تشعرين بالراحة مع جسمك؟',
  qs6h: 'صورة الجسم بعد الولادة.',
  qs7: 'هل مررتم بلحظات حميمية غير جنسية؟',
  qs7h: 'عناق، ملاطفة، حنان.',
  qs8: 'هل يؤثر التعب على حياتكم الحميمية؟',
  qs8h: 'تأثير الإرهاق.',
  qs9: 'هل ناقشتم موضوع منع الحمل؟',
  qs9h: 'التواصل حول الوقاية.',
  qs10: 'هل تشعرين أنك مرغوبة؟',
  qs10h: 'الشعور بالجاذبية.',

  res_global: 'عام',
  res_global_index: 'المؤشر العام لتوازن الزوجين',
  res_analysis: 'تحليل مفصل',
  res_psycho: 'نفسي',
  res_conjugal: 'زوجي',
  res_sexual: 'جنسي',
  res_explanation: 'شرح مخصص',
  res_first_eval_msg: 'أكملي تقييماتك الأولى للحصول على تحليل مخصص.',
  res_excellent: 'ممتاز',
  res_bon: 'جيد',
  res_moyen: 'متوسط',
  res_faible: 'ضعيف',
  res_orientation: 'توجيه موصى به',
  res_consult: 'نتيجة {types} ضعيفة. استشيري متخصصاً.',

  lib_title: 'المكتبة',
  lib_subtitle: 'نصائح الخبراء لكل مرحلة.',
  lib_search: 'البحث عن مقال...',
  lib_timeline: 'الجدول الزمني لما بعد الولادة',
  lib_all: 'الكل',
  lib_mental_health: 'الصحة النفسية',
  lib_sexuality: 'الحياة الجنسية',
  lib_couple_life: 'حياة الزوجين',
  lib_breastfeeding: 'الرضاعة',
  lib_featured: 'مقال مميز',
  lib_postpartum_title: 'ما بعد الولادة المباشر',
  lib_postpartum_desc: 'فهم تغيرات الساعات الـ 48 الأولى.',
  lib_read_more: 'اقرأي المزيد ←',
  lib_breathing: 'تمارين التنفس بعد الولادة',
  lib_sleep: 'التعامل مع قلة النوم',
  lib_communication: 'التواصل في الزوجين',
  lib_comm_desc: 'الحفاظ على الرابط بعد وصول الطفل.',
  lib_partner_role: 'دور الشريك',
  lib_intimacy: 'استعادة العلاقة الحميمية',
  lib_content_period: 'محتوى',
  lib_months: 'أشهر',

  prof_info: 'المعلومات',
  prof_age: 'العمر',
  prof_sex: 'الجنس',
  prof_marriage: 'مدة الزواج',
  prof_baby: 'عمر الطفل',
  prof_partner2: 'الشريك 2',
  prof_not_set: 'غير محدد',
  prof_stats: 'الإحصائيات',
  prof_evaluations: 'التقييمات',
  prof_articles: 'المقالات',
  prof_streak: 'أيام المتابعة',
  prof_settings: 'الإعدادات',
  prof_notif: 'الإشعارات',
  prof_lang: 'اللغة',
  prof_version: 'الإصدار',

  sf_title: 'مساعدة القابلة',
  sf_subtitle: 'نصائح مهنية لما بعد الولادة',
  sf_all: 'الكل',
  sf_postpartum: 'ما بعد الولادة',
  sf_breastfeeding: 'الرضاعة',
  sf_contraception: 'منع الحمل',
  sf_sexuality: 'الحياة الجنسية',
  sf_alerts: '⚠️ تنبيهات',

  sft1_title: 'التعافي بعد الولادة',
  sft1_text: 'الأسابيع الأولى حاسمة. خذي قسطاً من الراحة واستمعي لجسمك. النزيف يستمر 4-6 أسابيع. استشيري في حالة الحمى أو الآلام الشديدة.',
  sft2_title: 'الرضاعة الطبيعية',
  sft2_text: 'الإرضاع في الساعة الأولى. أرضعي عند الطلب. في حالة الألم، تحققي من وضعية الإرضاع. اطلبي مساعدة مستشارة الرضاعة.',
  sft3_title: 'منع الحمل بعد الولادة',
  sft3_text: 'يمكن العودة بعد 21 يوماً. الخيارات: اللولب، حبوب البروجسترون، الغرسة. الرضاعة الحصرية ليست وسيلة منع حمل موثوقة.',
  sft4_title: 'استئناف العلاقة الجنسية',
  sft4_text: 'لا يوجد موعد إلزامي. الجفاف المهبلي طبيعي. استخدمي مزلقاً. تحدثي مع شريكك.',
  sft5_title: 'علامات إنذار ⚠️',
  sft5_text: 'استشيري فوراً إذا: حمى >38 درجة، نزيف غزير، ألم شديد، حزن >أسبوعين، أفكار مظلمة، صعوبة في التعلق بالطفل.',
  sft6_title: 'كآبة الأمومة مقابل الاكتئاب',
  sft6_text: 'كآبة الأمومة (ي3-ي10): طبيعية وعابرة. اكتئاب ما بعد الولادة (>أسبوعين): حزن عميق، فقدان الاهتمام. تحدثي مع متخصص.',
  sft7_title: 'احتقان الثدي',
  sft7_text: 'شائع في ي3-ي5. كمادات دافئة قبل الرضاعة وباردة بعدها. تدليك تحت الدوش. أرضعي بشكل متكرر.',
  sft8_title: 'إعادة تأهيل العجان',
  sft8_text: 'موصى بها بعد أي ولادة، بدءاً من 6-8 أسابيع. تمنع السلس وتحسن الراحة الحميمية.',

  daily_title: 'كيف تشعرين؟',
  daily_subtitle: 'سجلي مزاجك اليومي.',
  daily_mood: 'مزاج اليوم',
  daily_exhausted: 'منهكة',
  daily_sad: 'حزينة',
  daily_neutral: 'عادي',
  daily_good: 'جيدة',
  daily_great: 'رائعة',
  daily_stress: 'مستوى التوتر',
  daily_conjugal: 'الرضا الزوجي',
  daily_intimate: 'الرضا الحميمي',
  daily_save: 'حفظ المتابعة',
  daily_saved: 'تم الحفظ!',
  daily_evolution: 'التطور الأخير',
  daily_satisfaction: 'الرضا',
  daily_stress_label: 'التوتر',
  daily_history: 'السجل الأخير',
  daily_no_entries: 'لا توجد إدخالات. ابدأي المتابعة أعلاه!',

  plan_title: 'خطة مخصصة',
  plan_subtitle: 'تمارين ونصائح مكيّفة حسب نتائجك',
  plan_days: 'يوم',
  plan_focus: 'المحاور ذات الأولوية',
  plan_focus_desc: 'بناءً على نتائجك، نوصي بالتركيز على:',
  plan_activities: 'الأنشطة',
  plan_completed: 'أنشطة مكتملة',
  plan_psycho_focus: 'الرفاه النفسي',
  plan_comm_focus: 'التواصل الزوجي',
  plan_pp_focus: 'مرافقة ما بعد الولادة',

  checkup_monthly: 'تقرير شهري',
  checkup_global_score: 'النتيجة العامة',
  checkup_by_dimension: 'النتائج حسب البعد',
  checkup_evolution: 'تطور النتائج',
  checkup_recommendations: 'التوصيات',
  checkup_start_plan: 'بدء خطة مخصصة',
  checkup_see_results: 'عرض النتائج المفصلة',
  checkup_trend_up: '↑ في ارتفاع',
  checkup_trend_down: '↓ في انخفاض',
  checkup_trend_stable: '= مستقر',
  checkup_trend_new: 'جديد',

  alerts_title: 'التنبيهات والتوجيه',
  alerts_subtitle: 'متابعة ذكية لصحتك',
  alerts_all_good: 'كل شيء على ما يرام! ✨',
  alerts_none: 'لا توجد تنبيهات حالياً. تابعي المتابعة المنتظمة.',
  alerts_back_home: 'العودة للرئيسية',
  alerts_important: 'تذكير مهم',
  alerts_disclaimer: 'NurtureFlow هو أداة للوقاية والتوعية. في حالة الضيق، اتصلي فوراً بمتخصص صحي أو بالرقم 3114.',
  alerts_alert: 'تنبيه',
  alerts_alerts: 'تنبيهات',
  alerts_critical: 'حرج',
  alerts_criticals: 'حرجة',
  alerts_warning: 'تحذير',
  alerts_warnings: 'تحذيرات',

  admin_title: 'إدارة NurtureFlow',
  admin_subtitle: 'نظرة عامة على المنصة',
  admin_dashboard: 'لوحة التحكم',
  admin_couples: 'أزواج مسجلون',
  admin_active: 'نشطون (7 أيام)',
  admin_evals: 'تقييمات',
  admin_daily: 'متابعات يومية',
  admin_avg_scores: 'متوسط النتائج العامة',
  admin_score_distrib: 'توزيع النتائج',
  admin_evals_by_type: 'التقييمات حسب النوع',
  admin_recent_couples: 'أزواج حديثون',
  admin_restricted: 'وصول مقيد',
  admin_restricted_msg: 'هذا القسم مخصص للمسؤول فقط.',
  admin_info: 'المعلومات',
  admin_return: 'رجوع',

  nc_title: 'إنشاء زوجين جديدين',
  nc_subtitle: 'تسجيل زوجين في القاعدة',
  nc_create: 'إنشاء الزوجين',
  nc_creating: 'جارٍ الإنشاء...',
  nc_success: 'تم إنشاء الزوجين بنجاح!',
  nc_created: 'تم الإنشاء!',

  misc_just_now: 'الآن',
  misc_ago_min: 'منذ {n} دقيقة',
  misc_ago_hours: 'منذ {n} ساعة',
  misc_yesterday: 'أمس',
  misc_ago_days: 'منذ {n} يوم',
  misc_loading: 'جارٍ التحميل...',
  misc_error: 'خطأ',
  misc_back: 'رجوع',
  misc_min_read: 'دقيقة قراءة',
  misc_period: 'الفترة',
  misc_back_library: 'العودة للمكتبة',
  misc_video: 'فيديو',
  misc_guide: 'دليل',
  misc_article: 'مقال',

  // Results HTML static
  res_global: 'عام',
  res_analysis: 'تحليل مفصّل',
  res_explanation: 'شرح مخصص',
  res_psychologique: 'نفسي',
  res_conjugal: 'زوجي',
  res_sexuel: 'جنسي',

  // Library
  lib_months_unit: 'أشهر',

  // Splash
  splash_tagline: 'من الحياة الزوجية إلى الأبوة',

  // Register placeholders
  auth_marriage_placeholder: 'مدة الزواج (مثال: 3 سنوات)',
  auth_baby_placeholder: 'عمر الطفل (مثال: 4 أشهر)',

  // Error messages
  err_fill_all: 'يرجى ملء جميع الحقول',
  err_pwd_mismatch: 'كلمتا المرور غير متطابقتين',
  err_required: 'الاسم والبريد وكلمة المرور مطلوبة',
  err_server: 'خطأ في الخادم',

  // Home
  home_evals_text: '{n}/3 تقييمات مكتملة',
  home_last_eval_title: 'آخر تقييم',
  home_first_eval_title: 'التقييم الأول',
  home_first_eval_text: 'ابدأي تقييمك الأول لاكتشاف ملفك الشخصي كزوجين.',
  home_score_label: 'النتيجة',
  home_new_modules: 'وحدات جديدة',
  home_weeks: 'الأسابيع أ1-أ12',
  home_journal: 'دفتر اليوميات',
  home_scales: 'المقاييس السريرية',
  home_tunisian: 'الزاوية التونسية',

  // Results explanations
  res_transition: 'علاقتكم تمر بمرحلة انتقالية ',
  res_resilience: 'بمرونة كبيرة. ',
  res_positive: 'بطريقة إيجابية. ',
  res_challenges: 'مع بعض التحديات. ',
  res_excellent_psycho: 'رفاه نفسي ممتاز ({score}%). ',
  res_low_psycho: 'رفاهك النفسي ({score}%) يحتاج اهتماماً خاصاً. ',
  res_low_conjugal: 'البعد الزوجي ({score}%) يمكن تعزيزه. ',
  res_low_sexual: 'البعد الحميمي ({score}%) يستحق المرافقة. ',
  res_first_eval_long: 'أكملي تقييماتك الأولى للحصول على تحليل مخصص.',
  res_orientation_title: 'توجيه موصى به',
  res_orientation_text: 'نتيجة {types} ضعيفة. استشيري متخصصاً.',

  // New Couple
  nc_partner1: 'الشريك 1',
  nc_partner2: 'الشريك 2',
  nc_couple_info: 'معلومات الزوجين',
  nc_security: 'الأمان',
  nc_firstname: 'الاسم الأول',
  nc_email: 'البريد الإلكتروني',
  nc_age: 'العمر',
  nc_woman: 'أنثى',
  nc_man: 'ذكر',

  // Suivi
  daily_days_dim: 'أحد',
  daily_days_lun: 'اثنين',
  daily_days_mar: 'ثلاثاء',
  daily_days_mer: 'أربعاء',
  daily_days_jeu: 'خميس',
  daily_days_ven: 'جمعة',
  daily_days_sam: 'سبت',
  daily_conj_label: 'زوجي',

  // Plan
  plan_loading_error: 'خطأ في تحميل الخطة.',
  plan_focus_psycho: 'الرفاه النفسي',
  plan_focus_comm: 'التواصل الزوجي',
  plan_focus_pp: 'مرافقة ما بعد الولادة',

  // Checkup
  checkup_generating: 'إنشاء التقرير...',
  checkup_psycho: 'نفسي',
  checkup_conjugal: 'زوجي',
  checkup_sexual: 'جنسي',
  checkup_no_data: 'أكملي تقييماً واحداً على الأقل لإنشاء تقريرك.',

  // Alerts
  alerts_loading_error: 'خطأ في تحميل التنبيهات.',

  // Admin
  admin_age_p1: 'عمر ش1',
  admin_sex_p1: 'جنس ش1',
  admin_age_p2: 'عمر ش2',
  admin_sex_p2: 'جنس ش2',
  admin_marriage: 'الزواج',
  admin_baby_age: 'عمر الطفل',
  admin_no_eval: 'لا تقييمات',
  admin_no_daily: 'لا متابعات',
  admin_loading_error: 'خطأ في التحميل.',
  admin_evals_count: 'التقييمات ({n})',
  admin_daily_count: 'المتابعة اليومية ({n})',
  admin_psycho: 'نفسي',

  // Timeline article
  timeline_article_not_found: 'المقال غير موجود.',
  timeline_read_time: '{n} دقيقة قراءة',
  timeline_period: 'الفترة {period} أشهر',

  // Semaines
  sem_title: 'أسابيع ما بعد الولادة',
  sem_week: 'الأسبوع',
  sem_medical: 'المتابعة الطبية',
  sem_maman: 'للأم',
  sem_couple: 'للزوجين',
  sem_bebe: 'رسالة الطفل',
  sem_solutions: 'حلول عملية',
  sem_prev: '→ السابق',
  sem_next: 'التالي ←',
  sem_week_of: 'الأسبوع {n} من 12',

  // Journal
  journal_title: 'دفتر اليوميات',
  journal_expression: 'مساحة للتعبير',
  journal_expression_desc: 'مساحة آمنة للتعبير عن مشاعركم بصدق وحب.',
  journal_our_journal: 'دفتر يومياتنا',
  journal_live: 'تحديث مباشر',
  journal_maman: '♀ الأم',
  journal_partner: '♂ الشريك',
  journal_today_feel: 'اليوم أشعر بـ:',
  journal_need: 'ما أحتاجه:',
  journal_need_placeholder: 'مثال: قليل من النوم، عناق دافئ...',
  journal_sweet: 'كلمة حلوة لشريكي:',
  journal_sweet_placeholder: 'مثال: شكراً على الرضعة الليلية...',
  journal_save: 'حفظ حالتي',
  journal_saved_notes: 'ملاحظات الأسبوع المحفوظة:',
  journal_no_notes: 'لا توجد ملاحظات حالياً. عبّري عن مشاعرك أعلاه.',
  journal_need_label: 'الحاجة',
  journal_select_mood: 'اختاري مزاجك!',

  // Échelles
  scales_title: 'المقاييس السريرية',
  scales_tools: 'أدوات التقييم السريري',
  scales_measure: 'القياس للمرافقة الأفضل',
  scales_desc: 'استبيان PISQ-12 (الحياة الجنسية) ومقياس RAS (الرضا الزوجي) يتيحان لك قياس حالة حياتك الحميمية.',
  scales_current_score: 'نتيجتك الحالية',
  scales_out_of: 'من {max} (الإجابات: {answered}/{total})',
  scales_diag: 'التشخيص والنصائح:',
  scales_low: '⚠️ نتيجة ضعيفة',
  scales_moderate: '⚡ نتيجة متوسطة',
  scales_good: '✅ نتيجة جيدة',
  scales_excellent: '🌟 نتيجة ممتازة',
  scales_pisq12_title: '❤ مقياس PISQ-12',
  scales_pisq12_sub: '(الحياة الجنسية)',
  scales_ras_title: '🤝 مقياس RAS',
  scales_ras_sub: '(الرضا)',
  scales_pisq12_q_title: 'استبيان PISQ-12: الحياة الجنسية بعد الولادة',
  scales_ras_q_title: 'استبيان RAS: الرضا الزوجي',
  scales_instruction: 'يرجى اختيار التكرار الأنسب لوضعك الحالي.',
  scales_calculate: 'حساب وتحليل',
  scales_reset: 'إعادة ضبط الاختبار',
  scales_privacy: 'احترام الخصوصية:',
  scales_privacy_text: 'لا يتم إرسال أي بيانات إلى خادم. يتم حساب النتائج محلياً لضمان سرية بياناتك.',
  scales_never: 'أبداً',
  scales_rarely: 'نادراً',
  scales_sometimes: 'أحياناً',
  scales_frequently: 'غالباً',
  scales_always: 'دائماً',
  scales_all_answered: 'تمت الإجابة على جميع الأسئلة',
  scales_remaining: 'يتبقى {n} أسئلة بدون إجابة',
  scales_partial_warning: 'لم تتم الإجابة على جميع الأسئلة. النتيجة جزئية.',

  // Tounsi
  tounsi_title: 'الزاوية التونسية',
  tounsi_wisdom: 'حكمة من عندنا',
  tounsi_main_title: 'زاوية الراحة و"بالتونسي"',
  tounsi_main_desc: 'مزج الدقة الطبية للقابلة التونسية مع دفء تقاليدنا الغذائية والروحية.',
  tounsi_paroles_title: 'كلمات دافئة',
  tounsi_paroles_ar: 'كلام دافي',
  tounsi_generator: 'مُولّد الراحة',
  tounsi_generator_desc: 'التعب يثقل الزوجين؟ انقري لتوليد كلمة حنونة تقليدية بالتونسي لتهدئة القلوب.',
  tounsi_generate_btn: 'توليد كلمة جديدة',
  tounsi_nefsa_title: 'حمية النفاسة (النفاسة)',
  tounsi_nefsa_sub: 'دعم الحليب والطاقة',
  tounsi_articles: 'مقالات الراحة',
  tounsi_footer: '© 2026 NurtureFlow — من الحياة الزوجية إلى الأبوة.',
  tounsi_footer_sub: 'صُمّم للإرشاد والدعم وتشجيع الحوار البنّاء. لا يُغني عن استشارة القابلة أو الطبيب.',

  // Profile static
  prof_notifications: 'الإشعارات',
  prof_lang_display: 'اللغة: العربية',
  prof_ans: 'سنة',

  // Drawer extra
  drawer_weeks: 'الأسابيع أ1-أ12',
  drawer_journal: 'دفتر اليوميات',
  drawer_scales: 'المقاييس السريرية',
  drawer_tunisian: 'الزاوية التونسية',

  // Breastfeeding module
  bf_module_title: 'دليل الرضاعة الشامل',
  bf_module_desc: 'دليل كامل، اختبار، خرافات ويوميات',
  bf_title: 'الرضاعة الطبيعية',
  bf_subtitle: 'دليل شامل للأم المرضعة',
  bf_tab_guide: 'الدليل',
  bf_tab_myths: 'خرافات',
  bf_tab_quiz: 'اختبار',
  bf_tab_log: 'يوميات',
  bf_chapter: 'الفصل',
  bf_myths_title: 'خرافات وحقائق عن الرضاعة',
  bf_myths_desc: 'اضغطي على كل بطاقة لاكتشاف الحقيقة',
  bf_myth: 'خرافة',
  bf_reality: 'حقيقة',
  bf_quiz_title: 'اختبار تقييم الرضاعة',
  bf_quiz_desc: 'أجيبي على 18 سؤال لتقييم جودة الرضاعة',
  bf_yes: 'نعم',
  bf_no: 'لا',
  bf_quiz_excellent: 'الرضاعة تسير بشكل ممتاز',
  bf_quiz_good: 'صعوبات بسيطة',
  bf_quiz_attention: 'يوصى بالاستشارة',
  bf_quiz_urgent: 'تقييم مهني عاجل',
  bf_quiz_medical_alert: 'تنبيه طبي',
  bf_quiz_retry: 'إعادة الاختبار',
  bf_log_title: 'يوميات الرضاعة',
  bf_log_today: 'تسجيل اليوم',
  bf_log_feeds: 'عدد الرضعات',
  bf_log_duration: 'مدة الرضعة',
  bf_log_pumped: 'كمية الحليب المشفوط',
  bf_log_mood: 'حالتك المزاجية',
  bf_log_notes_placeholder: 'ملاحظات شخصية...',
  bf_log_save: 'حفظ',
  bf_log_saved: 'تم الحفظ!',
  bf_log_weekly: 'إحصائيات الأسبوع',
  bf_log_avg_feeds: 'معدل الرضعات',
  bf_log_days: 'أيام مسجلة',
  bf_log_pumped_total: 'مشفوط',
  bf_log_history: 'السجل',
  bf_log_feeds_short: 'رضعات',
  bf_log_empty: 'لا توجد تسجيلات بعد. ابدأي التسجيل أعلاه!',

  // Sexuality module
  sx_module_title: 'الحياة الجنسية والعناية بعد الولادة',
  sx_module_desc: 'دليل الحياة الجنسية والعناية بشق العجان',
  sx_title: 'الحياة الجنسية بعد الولادة',
  sx_subtitle: 'نصائح وإرشادات مهنية',
  sx_tab_guide: 'الدليل',
  sx_tab_myths: 'خرافات',
  sx_tab_consult: 'استشارة',
  sx_myths_title: 'خرافات وحقائق',
  sx_myths_desc: 'اضغطي على كل بطاقة لاكتشاف الحقيقة',
  sx_when_consult: 'متى يجب استشارة الطبيب؟',
  sx_consult_intro: 'يُنصح باستشارة أخصائية التوليد أو الطبيب إذا وُجد:',
  sx_consult_msg: 'لا تترددي في استشارة أخصائية التوليد أو طبيبك للحصول على المساعدة اللازمة.',

  // Medical alerts
  alert_bf_fever_title: 'حرارة أكثر من 38 درجة',
  alert_bf_fever_msg: 'إذا ترافق احتقان الثدي مع حرارة أكثر من 38 درجة يجب استشارة مختص فوراً.',
  alert_bf_redness_title: 'احمرار شديد بالثدي',
  alert_bf_redness_msg: 'احمرار متزايد أو تورم شديد بالثدي قد يشير إلى التهاب. يُنصح بالتواصل مع أخصائية توليد.',
  alert_bf_lump_title: 'كتلة مؤلمة بالثدي',
  alert_bf_lump_msg: 'وجود كتلة مؤلمة بالثدي يستوجب تقييماً طبياً عاجلاً.',
  alert_bf_refuse_title: 'رفض الطفل للرضاعة',
  alert_bf_refuse_msg: 'إذا رفض الطفل الرضاعة بشكل مستمر يُنصح باستشارة مختص.',
  alert_bf_weight_title: 'نقص وزن الطفل',
  alert_bf_weight_msg: 'نقص وزن الطفل أو عدم زيادته بشكل طبيعي قد يتطلب تقييم الرضاعة.',
  alert_epis_title: 'علامات خطر بشق العجان',
  alert_epis_msg: 'احمرار متزايد، إفرازات ذات رائحة كريهة، حرارة > 38°C، انفتاح الجرح — استشيري الطبيب فوراً.',
  alert_sx_pain_title: 'ألم مستمر أثناء العلاقة',
  alert_sx_pain_msg: 'الألم المستمر أثناء العلاقة الجنسية يحتاج استشارة مختص.',
  alert_ppd_title: 'اكتئاب ما بعد الولادة',
  alert_ppd_msg: 'حزن عميق أو فقدان الاهتمام لأكثر من أسبوعين يحتاج متابعة مختص.',
  alert_action_bf: 'فتح دليل الرضاعة',
  alert_action_sx: 'فتح دليل العناية',
  alert_action_eval: 'بدء التقييم',
  alerts_medical_intro: 'تنبيهات طبية مهمة يجب الانتباه إليها. استشيري المختص في حال ظهور أي من هذه العلامات.',

  // Newborn module
  nb_module_title: 'العناية بالمولود الجديد',
  nb_module_desc: 'دليل شامل للعناية بالمولود',
  nb_title: 'المولود الجديد',
  nb_subtitle: 'دليل العناية بالمولود',
  nb_tab_guide: 'الدليل',
  nb_tab_myths: 'خرافات',
  nb_myths_title: 'خرافات وحقائق عن المولود',
  nb_myths_desc: 'اضغطي على كل بطاقة لاكتشاف الحقيقة',

  // Myths module
  my_module_title: 'خرافات وحقائق',
  my_module_desc: 'جميع الخرافات الشائعة مع التصحيح العلمي',
  my_title: 'خرافات وحقائق',
  my_subtitle: '20 خرافة شائعة مع الحقيقة العلمية',
  my_tap_hint: 'اضغطي على أي بطاقة لاكتشاف الحقيقة',
  my_footer: 'المعلومات مبنية على توصيات منظمة الصحة العالمية والممارسات السريرية.',

  // Baby Age Widget
  baby_title: 'عمر المولود',
  baby_enter_info: 'أدخلي تاريخ وساعة الولادة',
  baby_date: 'تاريخ الولادة',
  baby_time: 'ساعة الولادة',
  baby_save: 'حفظ',
  baby_age_title: 'عمر طفلك',
  baby_months: 'شهر',
  baby_days: 'يوم',
  baby_hours: 'ساعة',
  baby_minutes: 'دقيقة',
  baby_newborn_msg: 'مبروك! طفلك حديث الولادة ❤️',
  baby_weeks_old: 'عمر الطفل: {n} أسابيع',

  // Notifications
  notif_title: 'الإشعارات',
  notif_clear: 'مسح الكل',
  notif_empty: 'لا توجد إشعارات حالياً.',
  notif_just_now: 'الآن',
  notif_min_ago: 'د',
  notif_hrs_ago: 'س',
  notif_days_ago: 'ي',
  notif_welcome: 'مرحباً بكم في NurtureFlow! 🌸 مساحتكم الزوجية بانتظاركم.',
  notif_eval_reminder: 'لا تنسي ملء تقييمك الأسبوعي! 📋',
  notif_baby_born: 'تهانينا على ولادة طفلكم! 🎉',
  notif_baby_1week: 'طفلكم أكمل أسبوعاً! الأيام الأولى ثمينة. 🎊',
  notif_baby_2weeks: 'طفلكم أكمل أسبوعين! فكري بالمتابعة بعد الولادة. 🌟',
  notif_baby_1month: 'شهر سعيد لطفلكم! 🎂',
  notif_baby_2months: 'طفلكم أكمل شهرين! فكري بالتطعيم الأول. 🌸',
  notif_baby_3months: 'تهانينا، 3 أشهر بالفعل! فصل من السعادة. 🎈',
  notif_tip_water: 'تذكري أن تشربي الماء بكثرة اليوم! الرضاعة تزيد الحاجة للماء.',
  notif_tip_breathe: 'خصصي 5 دقائق للتنفس العميق. صحتك تهم.',
  notif_tip_hug: 'حضن 20 ثانية يُفرز الأوكسيتوسين. احضني شريكك!',
  notif_tip_sleep: 'نامي عندما ينام الطفل. النوم حليفك الأفضل.',
  notif_tip_breastfeed: 'وضعية مريحة للرضاعة: ظهر مسنود، وسائد تحت الذراعين.',
  notif_tip_walk: 'نزهة قصيرة 15 دقيقة تحسن المزاج وتقوي الرابط مع الطفل.',
  notif_tip_talk: 'خصصي 10 دقائق للحديث مع شريكك. التواصل يقوي الزوجين.',
},

// ═══════════════════════════════════════
//  ENGLISH
// ═══════════════════════════════════════
en: {
  app_name: 'NurtureFlow',
  app_tagline: 'From Couplehood to Parenthood',

  auth_email: 'Email',
  auth_password: 'Password',
  auth_login: 'Sign in',
  auth_no_account: 'Don\'t have an account?',
  auth_create_account: 'Create a couple account',
  auth_create_title: 'Create your couple space',
  auth_partner1: 'PARTNER 1',
  auth_partner2: 'PARTNER 2',
  auth_couple_info: 'COUPLE INFO',
  auth_security: 'SECURITY',
  auth_firstname: 'First name',
  auth_age: 'Age',
  auth_woman: 'Female',
  auth_man: 'Male',
  auth_marriage_duration: 'Marriage duration (e.g. 3 years)',
  auth_baby_age: 'Baby\'s age (e.g. 4 months)',
  auth_password_min: 'Password (min 4 characters)',
  auth_password_confirm: 'Confirm password',
  auth_create_btn: 'Create account',
  auth_fill_all: 'Please fill in all fields',
  auth_pwd_mismatch: 'Passwords do not match',
  auth_required: 'Name, email and password are required',

  nav_home: 'Home',
  nav_results: 'Results',
  nav_library: 'Library',
  nav_profile: 'Profile',

  drawer_home: 'Home',
  drawer_evaluations: 'Evaluations',
  drawer_plan: 'Personal Plan',
  drawer_checkup: 'Couple Check-Up',
  drawer_daily: 'Daily Tracking',
  drawer_alerts: 'Alerts',
  drawer_sage_femme: 'Midwife Assistant',
  drawer_library: 'Library',
  drawer_settings: 'Settings',
  drawer_admin: 'Admin Dashboard',
  drawer_new_couple: 'New Couple',
  drawer_logout: 'Sign out',
  drawer_welcome: 'Welcome',
  drawer_couple_since: 'Couple since',

  home_hello: 'Hello',
  home_ready: 'Ready for your guidance?',
  home_global_progress: 'Overall progress',
  home_evals_completed: 'evaluations completed',
  home_tip_of_day: 'Tip of the day',
  home_tip_title: 'Maintaining emotional connection',
  home_tip_desc: 'Small daily rituals strengthen your bond.',
  home_evaluations: 'SELF-ASSESSMENTS',
  home_psycho: 'Psychological',
  home_conjugal: 'Conjugal',
  home_sexual: 'Sexual',
  home_first_eval: 'First Assessment',
  home_first_eval_desc: 'Start your first assessment to discover your profile.',
  home_last_eval: 'Last Assessment',
  home_daily_tracking: 'Daily Tracking',
  home_midwife: 'Midwife',
  home_score: 'Score',

  q_previous: 'Previous',
  q_next: 'Next',
  q_finish: 'Finish',
  q_question: 'Question',
  q_never: 'Never',
  q_rarely: 'Rarely',
  q_sometimes: 'Sometimes',
  q_often: 'Often',
  q_always: 'Always',

  qt_psycho: 'Psychological Well-being',
  qt_conjugal: 'Conjugal Relationship',
  qt_sexual: 'Postpartum Intimacy',

  qp1: 'How would you rate your stress level this week?',
  qp1h: 'Think about moments of tension or worry.',
  qp2: 'Have you felt excessive fatigue recently?',
  qp2h: 'Physical and/or mental fatigue related to parenthood.',
  qp3: 'How would you describe your general mood?',
  qp3h: 'Think about your overall emotional state.',
  qp4: 'Do you feel anxious about parenting responsibilities?',
  qp4h: 'Worry related to your role as a parent.',
  qp5: 'Are you adapting well to changes since baby arrived?',
  qp5h: 'Your ability to manage the new routine.',
  qp6: 'Have you experienced moments of discouragement?',
  qp6h: 'Feeling unable to cope.',
  qp7: 'Do you take time for yourself?',
  qp7h: 'Moments of relaxation, hobbies, rest.',
  qp8: 'Are you sleeping enough to feel rested?',
  qp8h: 'Quality and duration of your sleep.',
  qp9: 'Do you feel in control of your daily life?',
  qp9h: 'Sense of mastery over your life.',
  qp10: 'Do you feel emotionally supported?',
  qp10h: 'Support from family, friends, partner.',

  qc1: 'How do you rate communication with your partner?',
  qc1h: 'Your exchanges over the past 7 days.',
  qc2: 'Do you feel supported by your partner?',
  qc2h: 'Practical and emotional support.',
  qc3: 'Have you experienced conflicts or disagreements?',
  qc3h: 'Tensions, arguments, misunderstandings.',
  qc4: 'Are you satisfied with your relationship?',
  qc4h: 'Overall satisfaction.',
  qc5: 'Have you spent quality time together?',
  qc5h: 'Shared moments without parental duties.',
  qc6: 'Do you share parenting tasks equally?',
  qc6h: 'Distribution of care and tasks.',
  qc7: 'Can you easily express your needs?',
  qc7h: 'Open communication about your expectations.',
  qc8: 'Do you feel heard by your partner?',
  qc8h: 'Attention and understanding.',
  qc9: 'Have you shared moments of joy together?',
  qc9h: 'Complicity and shared happiness.',
  qc10: 'Do you feel complicity with your partner?',
  qc10h: 'Connection and unity.',

  qs1: 'Do you feel desire for your partner?',
  qs1h: 'Attraction and desire for intimacy.',
  qs2: 'Are you satisfied with your current intimate life?',
  qs2h: 'Level of satisfaction.',
  qs3: 'Do you openly communicate about your sexuality?',
  qs3h: 'Ability to discuss the topic.',
  qs4: 'Have you encountered physical difficulties?',
  qs4h: 'Pain, discomfort, changes.',
  qs5: 'Do you feel apprehension or pain?',
  qs5h: 'Fears about resuming intimacy.',
  qs6: 'Are you comfortable with your body?',
  qs6h: 'Postpartum body image.',
  qs7: 'Have you had non-sexual intimate moments?',
  qs7h: 'Cuddling, caressing, tenderness.',
  qs8: 'Does fatigue affect your intimate life?',
  qs8h: 'Impact of exhaustion.',
  qs9: 'Have you discussed contraception?',
  qs9h: 'Communication about prevention.',
  qs10: 'Do you feel desirable?',
  qs10h: 'Feeling attractive.',

  res_global: 'Global',
  res_global_index: 'Global Couple Balance Index',
  res_analysis: 'Detailed Analysis',
  res_psycho: 'Psychological',
  res_conjugal: 'Conjugal',
  res_sexual: 'Sexual',
  res_explanation: 'Personalized explanation',
  res_first_eval_msg: 'Complete your first assessments for a personalized analysis.',
  res_excellent: 'Excellent',
  res_bon: 'Good',
  res_moyen: 'Average',
  res_faible: 'Low',
  res_orientation: 'Recommended guidance',
  res_consult: '{types} score is low. Consult a professional.',

  lib_title: 'Library',
  lib_subtitle: 'Expert advice for every stage.',
  lib_search: 'Search for an article...',
  lib_timeline: 'POSTPARTUM TIMELINE',
  lib_all: 'All',
  lib_mental_health: 'Mental Health',
  lib_sexuality: 'Sexuality',
  lib_couple_life: 'Couple Life',
  lib_breastfeeding: 'Breastfeeding',
  lib_featured: 'Featured Article',
  lib_postpartum_title: 'The immediate postpartum',
  lib_postpartum_desc: 'Understanding the changes in the first 48 hours.',
  lib_read_more: 'Read more →',
  lib_breathing: 'Postnatal breathing',
  lib_sleep: 'Managing sleep deprivation',
  lib_communication: 'Couple communication',
  lib_comm_desc: 'Maintaining the bond after baby arrives.',
  lib_partner_role: 'The partner\'s role',
  lib_intimacy: 'Rediscovering intimacy',
  lib_content_period: 'CONTENT',
  lib_months: 'MONTHS',

  prof_info: 'INFORMATION',
  prof_age: 'Age',
  prof_sex: 'Gender',
  prof_marriage: 'Marriage duration',
  prof_baby: 'Baby\'s age',
  prof_partner2: 'Partner 2',
  prof_not_set: 'Not specified',
  prof_stats: 'STATISTICS',
  prof_evaluations: 'Evaluations',
  prof_articles: 'Articles',
  prof_streak: 'Days tracked',
  prof_settings: 'SETTINGS',
  prof_notif: 'Notifications',
  prof_lang: 'Language',
  prof_version: 'Version',

  sf_title: 'Midwife Assistant',
  sf_subtitle: 'Professional postpartum advice',
  sf_all: 'All',
  sf_postpartum: 'Postpartum',
  sf_breastfeeding: 'Breastfeeding',
  sf_contraception: 'Contraception',
  sf_sexuality: 'Sexuality',
  sf_alerts: '⚠️ Alerts',

  sft1_title: 'Postpartum recovery',
  sft1_text: 'The first weeks are crucial. Rest and listen to your body. Lochia lasts 4-6 weeks. Consult if fever or severe pain.',
  sft2_title: 'Breastfeeding',
  sft2_text: 'First feeding within the first hour. Feed on demand. If painful, check position and latch. Ask a lactation consultant.',
  sft3_title: 'Postpartum contraception',
  sft3_text: 'Can resume from day 21. Options: IUD, progestogen pill, implant. Exclusive breastfeeding is NOT a reliable contraception.',
  sft4_title: 'Resuming sexual activity',
  sft4_text: 'No mandatory delay. Vaginal dryness is normal. Use lubricant. Communicate with your partner.',
  sft5_title: 'Warning signs ⚠️',
  sft5_text: 'Consult immediately if: fever >38°C, heavy bleeding, severe pain, sadness >2 weeks, dark thoughts, difficulty bonding with baby.',
  sft6_title: 'Baby blues vs Depression',
  sft6_text: 'Baby blues (D3-D10): normal, temporary. Postpartum depression (>2 weeks): deep sadness, loss of interest. Talk to a professional.',
  sft7_title: 'Breast engorgement',
  sft7_text: 'Common around D3-D5. Warm compresses before feeding, cold after. Shower massage. Feed frequently.',
  sft8_title: 'Perineal rehabilitation',
  sft8_text: 'Recommended after any delivery, from 6-8 weeks. Prevents incontinence and improves intimate comfort.',

  daily_title: 'How are you feeling?',
  daily_subtitle: 'Record your daily mood.',
  daily_mood: 'TODAY\'S MOOD',
  daily_exhausted: 'Exhausted',
  daily_sad: 'Sad',
  daily_neutral: 'Neutral',
  daily_good: 'Good',
  daily_great: 'Great',
  daily_stress: 'Stress level',
  daily_conjugal: 'Conjugal satisfaction',
  daily_intimate: 'Intimate satisfaction',
  daily_save: 'Save my tracking',
  daily_saved: 'Saved!',
  daily_evolution: 'Recent evolution',
  daily_satisfaction: 'Satisfaction',
  daily_stress_label: 'Stress',
  daily_history: 'Recent history',
  daily_no_entries: 'No entries. Start tracking above!',

  plan_title: 'Personal Plan',
  plan_subtitle: 'Exercises and advice adapted to your scores',
  plan_days: 'days',
  plan_focus: 'Priority areas',
  plan_focus_desc: 'Based on your scores, we recommend focusing on:',
  plan_activities: 'ACTIVITIES',
  plan_completed: 'activities completed',
  plan_psycho_focus: 'psychological well-being',
  plan_comm_focus: 'conjugal communication',
  plan_pp_focus: 'postpartum support',

  checkup_monthly: 'MONTHLY REPORT',
  checkup_global_score: 'Global Score',
  checkup_by_dimension: 'SCORES BY DIMENSION',
  checkup_evolution: 'Score evolution',
  checkup_recommendations: 'RECOMMENDATIONS',
  checkup_start_plan: 'Start a Personal Plan',
  checkup_see_results: 'View detailed results',
  checkup_trend_up: '↑ Rising',
  checkup_trend_down: '↓ Falling',
  checkup_trend_stable: '= Stable',
  checkup_trend_new: 'New',

  alerts_title: 'Alerts & Guidance',
  alerts_subtitle: 'Smart wellness monitoring',
  alerts_all_good: 'All good! ✨',
  alerts_none: 'No alerts at the moment. Keep up your regular tracking.',
  alerts_back_home: 'Back to home',
  alerts_important: 'Important reminder',
  alerts_disclaimer: 'NurtureFlow is a prevention and awareness tool. In case of distress, immediately contact a health professional or call 3114.',
  alerts_alert: 'alert',
  alerts_alerts: 'alerts',
  alerts_critical: 'critical',
  alerts_criticals: 'critical',
  alerts_warning: 'warning',
  alerts_warnings: 'warnings',

  admin_title: 'NurtureFlow Administration',
  admin_subtitle: 'Platform overview',
  admin_dashboard: 'DASHBOARD',
  admin_couples: 'Registered couples',
  admin_active: 'Active (7d)',
  admin_evals: 'Evaluations',
  admin_daily: 'Daily trackings',
  admin_avg_scores: 'Global Average Scores',
  admin_score_distrib: 'Score Distribution',
  admin_evals_by_type: 'Evaluations by Type',
  admin_recent_couples: 'RECENT COUPLES',
  admin_restricted: 'Restricted access',
  admin_restricted_msg: 'This section is reserved for the administrator.',
  admin_info: 'INFORMATION',
  admin_return: 'Return',

  nc_title: 'Create new couple',
  nc_subtitle: 'Register a couple in the database',
  nc_create: 'Create couple',
  nc_creating: 'Creating...',
  nc_success: 'Couple created successfully!',
  nc_created: 'Created!',

  misc_just_now: 'Just now',
  misc_ago_min: '{n} min ago',
  misc_ago_hours: '{n}h ago',
  misc_yesterday: 'Yesterday',
  misc_ago_days: '{n} days ago',
  misc_loading: 'Loading...',
  misc_error: 'Error',
  misc_back: 'Back',
  misc_min_read: 'min read',
  misc_period: 'Period',
  misc_back_library: 'Back to library',
  misc_video: 'Video',
  misc_guide: 'Guide',
  misc_article: 'Article',

  // Results HTML static
  res_global: 'Global',
  res_analysis: 'Detailed Analysis',
  res_explanation: 'Personalized Explanation',
  res_psychologique: 'Psychological',
  res_conjugal: 'Conjugal',
  res_sexuel: 'Sexual',

  // Library
  lib_months_unit: 'months',

  // Splash
  splash_tagline: 'From Couplehood to Parenthood',

  // Register placeholders
  auth_marriage_placeholder: 'Marriage duration (e.g. 3 years)',
  auth_baby_placeholder: 'Baby\'s age (e.g. 4 months)',

  // Error messages
  err_fill_all: 'Please fill in all fields',
  err_pwd_mismatch: 'Passwords do not match',
  err_required: 'Name, email and password are required',
  err_server: 'Server error',

  // Home
  home_evals_text: '{n}/3 evaluations completed',
  home_last_eval_title: 'Last Assessment',
  home_first_eval_title: 'First Assessment',
  home_first_eval_text: 'Start your first assessment to discover your couple profile.',
  home_score_label: 'Score',
  home_new_modules: 'NEW MODULES',
  home_weeks: 'Weeks W1-W12',
  home_journal: 'Couple Journal',
  home_scales: 'Clinical Scales',
  home_tunisian: 'Tunisian Corner',

  // Results explanations
  res_transition: 'Your relationship is going through this transition phase ',
  res_resilience: 'with great resilience. ',
  res_positive: 'in a positive way. ',
  res_challenges: 'with some challenges to address. ',
  res_excellent_psycho: 'Excellent psychological well-being ({score}%). ',
  res_low_psycho: 'Your psychological well-being ({score}%) needs particular attention. ',
  res_low_conjugal: 'The conjugal dimension ({score}%) could be strengthened. ',
  res_low_sexual: 'The intimate dimension ({score}%) deserves support. ',
  res_first_eval_long: 'Complete your first assessments for a personalized analysis.',
  res_orientation_title: 'Recommended guidance',
  res_orientation_text: '{types} score is low. Consult a professional.',

  // New Couple
  nc_partner1: 'PARTNER 1',
  nc_partner2: 'PARTNER 2',
  nc_couple_info: 'COUPLE INFO',
  nc_security: 'SECURITY',
  nc_firstname: 'First name',
  nc_email: 'Email',
  nc_age: 'Age',
  nc_woman: 'Female',
  nc_man: 'Male',

  // Suivi
  daily_days_dim: 'Sun',
  daily_days_lun: 'Mon',
  daily_days_mar: 'Tue',
  daily_days_mer: 'Wed',
  daily_days_jeu: 'Thu',
  daily_days_ven: 'Fri',
  daily_days_sam: 'Sat',
  daily_conj_label: 'Conj',

  // Plan
  plan_loading_error: 'Error loading the plan.',
  plan_focus_psycho: 'psychological well-being',
  plan_focus_comm: 'conjugal communication',
  plan_focus_pp: 'postpartum support',

  // Checkup
  checkup_generating: 'Generating report...',
  checkup_psycho: 'Psychological',
  checkup_conjugal: 'Conjugal',
  checkup_sexual: 'Sexual',
  checkup_no_data: 'Complete at least one assessment to generate your report.',

  // Alerts
  alerts_loading_error: 'Error loading alerts.',

  // Admin
  admin_age_p1: 'Age P1',
  admin_sex_p1: 'Gender P1',
  admin_age_p2: 'Age P2',
  admin_sex_p2: 'Gender P2',
  admin_marriage: 'Marriage',
  admin_baby_age: 'Baby age',
  admin_no_eval: 'No evaluations',
  admin_no_daily: 'No tracking',
  admin_loading_error: 'Loading error.',
  admin_evals_count: 'EVALUATIONS ({n})',
  admin_daily_count: 'DAILY TRACKING ({n})',
  admin_psycho: 'Psycho',

  // Timeline article
  timeline_article_not_found: 'Article not found.',
  timeline_read_time: '{n} min read',
  timeline_period: 'Period {period} months',

  // Semaines
  sem_title: 'Postpartum Weeks',
  sem_week: 'WEEK',
  sem_medical: 'MEDICAL FOLLOW-UP',
  sem_maman: 'For Mom',
  sem_couple: 'For the Couple',
  sem_bebe: 'Baby\'s Message',
  sem_solutions: 'Practical Solutions',
  sem_prev: '← Previous',
  sem_next: 'Next →',
  sem_week_of: 'Week {n} of 12',

  // Journal
  journal_title: 'Couple Journal',
  journal_expression: 'Expression Space',
  journal_expression_desc: 'A safe space to communicate your feelings openly and with love.',
  journal_our_journal: 'Our Journal',
  journal_live: 'LIVE UPDATE',
  journal_maman: '♀ Mom',
  journal_partner: '♂ Partner',
  journal_today_feel: 'TODAY, I FEEL:',
  journal_need: 'WHAT I NEED:',
  journal_need_placeholder: 'E.g. Some sleep, a warm hug...',
  journal_sweet: 'SWEET WORD FOR MY PARTNER:',
  journal_sweet_placeholder: 'E.g. Thank you for the night feeding...',
  journal_save: 'SAVE MY STATE',
  journal_saved_notes: 'SAVED NOTES THIS WEEK:',
  journal_no_notes: 'No notes yet. Express your feelings above.',
  journal_need_label: 'Need',
  journal_select_mood: 'Select your mood!',

  // Échelles
  scales_title: 'Clinical Scales',
  scales_tools: 'CLINICAL ASSESSMENT TOOLS',
  scales_measure: 'Measure to Better Support',
  scales_desc: 'The PISQ-12 (Sexuality) and RAS Scale (Conjugal Satisfaction) questionnaires help you take the pulse of your intimacy.',
  scales_current_score: 'YOUR CURRENT SCORE',
  scales_out_of: 'out of {max} (Answered: {answered}/{total})',
  scales_diag: 'DIAGNOSIS \u0026 TAILORED ADVICE:',
  scales_low: '⚠️ LOW SCORE',
  scales_moderate: '⚡ MODERATE SCORE',
  scales_good: '✅ GOOD SCORE',
  scales_excellent: '🌟 EXCELLENT SCORE',
  scales_pisq12_title: '❤ PISQ-12 Scale',
  scales_pisq12_sub: '(Sexuality)',
  scales_ras_title: '🤝 RAS Scale',
  scales_ras_sub: '(Satisfaction)',
  scales_pisq12_q_title: 'PISQ-12 Questionnaire: Postpartum Sexuality',
  scales_ras_q_title: 'RAS Questionnaire: Conjugal Satisfaction',
  scales_instruction: 'Please select the frequency that best matches your current situation.',
  scales_calculate: 'CALCULATE \u0026 ANALYZE',
  scales_reset: 'Reset test',
  scales_privacy: 'Privacy:',
  scales_privacy_text: 'No data is sent to a server. Results are calculated locally to ensure data confidentiality.',
  scales_never: 'Never',
  scales_rarely: 'Rarely',
  scales_sometimes: 'Sometimes',
  scales_frequently: 'Frequently',
  scales_always: 'Always',
  scales_all_answered: 'All questions answered',
  scales_remaining: '{n} questions remaining',
  scales_partial_warning: 'Not all questions were answered. Result is partial.',

  // Tounsi
  tounsi_title: 'Tunisian Corner',
  tounsi_wisdom: 'OUR WISDOM',
  tounsi_main_title: 'Wellness Corner \u0026 "Bil Tounsi"',
  tounsi_main_desc: 'Blending the medical rigor of the Tunisian midwife with the warmth of our culinary and spiritual traditions.',
  tounsi_paroles_title: 'WARM WORDS',
  tounsi_paroles_ar: 'كلام دافي',
  tounsi_generator: 'The Comfort Generator',
  tounsi_generator_desc: 'Fatigue weighing on the couple? Click to generate a tender traditional word in Tunisian dialect to soothe hearts.',
  tounsi_generate_btn: 'Generate a new word',
  tounsi_nefsa_title: 'El Nefsa Diet (النفاسة)',
  tounsi_nefsa_sub: 'SUPPORTING MILK AND ENERGY',
  tounsi_articles: 'WELLNESS ARTICLES',
  tounsi_footer: '© 2026 NurtureFlow — From Couplehood to Parenthood.',
  tounsi_footer_sub: 'Created to guide, support and encourage dialogue. Does not replace professional medical advice.',

  // Profile static
  prof_notifications: 'Notifications',
  prof_lang_display: 'Language: English',
  prof_ans: 'years',

  // Drawer extra
  drawer_weeks: 'Weeks W1-W12',
  drawer_journal: 'Couple Journal',
  drawer_scales: 'Clinical Scales',
  drawer_tunisian: 'Tunisian Corner',

  // Breastfeeding module
  bf_module_title: 'Complete Breastfeeding Guide',
  bf_module_desc: 'Guide, quiz, myths & daily log',
  bf_title: 'Breastfeeding',
  bf_subtitle: 'Complete guide for breastfeeding mothers',
  bf_tab_guide: 'Guide',
  bf_tab_myths: 'Myths',
  bf_tab_quiz: 'Quiz',
  bf_tab_log: 'Log',
  bf_chapter: 'Chapter',
  bf_myths_title: 'Breastfeeding Myths & Facts',
  bf_myths_desc: 'Tap each card to discover the truth',
  bf_myth: 'Myth',
  bf_reality: 'Fact',
  bf_quiz_title: 'Breastfeeding Assessment Quiz',
  bf_quiz_desc: 'Answer 18 questions to evaluate breastfeeding quality',
  bf_yes: 'Yes',
  bf_no: 'No',
  bf_quiz_excellent: 'Breastfeeding is going great',
  bf_quiz_good: 'Minor difficulties',
  bf_quiz_attention: 'Consultation recommended',
  bf_quiz_urgent: 'Urgent professional assessment',
  bf_quiz_medical_alert: 'Medical Alert',
  bf_quiz_retry: 'Retake Quiz',
  bf_log_title: 'Breastfeeding Log',
  bf_log_today: 'Today\'s Entry',
  bf_log_feeds: 'Number of feeds',
  bf_log_duration: 'Feed duration',
  bf_log_pumped: 'Amount pumped',
  bf_log_mood: 'Your mood',
  bf_log_notes_placeholder: 'Personal notes...',
  bf_log_save: 'Save',
  bf_log_saved: 'Saved!',
  bf_log_weekly: 'Weekly Stats',
  bf_log_avg_feeds: 'Avg feeds/day',
  bf_log_days: 'Days logged',
  bf_log_pumped_total: 'pumped',
  bf_log_history: 'History',
  bf_log_feeds_short: 'feeds',
  bf_log_empty: 'No entries yet. Start logging above!',

  // Sexuality module
  sx_module_title: 'Post-Partum Sexuality & Care',
  sx_module_desc: 'Sexuality guide & episiotomy care',
  sx_title: 'Post-Partum Sexuality',
  sx_subtitle: 'Professional advice & guidance',
  sx_tab_guide: 'Guide',
  sx_tab_myths: 'Myths',
  sx_tab_consult: 'Consult',
  sx_myths_title: 'Myths & Facts',
  sx_myths_desc: 'Tap each card to discover the truth',
  sx_when_consult: 'When to See a Doctor?',
  sx_consult_intro: 'Consult a midwife or doctor if you experience:',
  sx_consult_msg: 'Don\'t hesitate to consult your midwife or doctor for the help you need.',

  // Medical alerts
  alert_bf_fever_title: 'Fever above 38°C',
  alert_bf_fever_msg: 'If breast engorgement is accompanied by fever above 38°C, consult a specialist immediately.',
  alert_bf_redness_title: 'Severe breast redness',
  alert_bf_redness_msg: 'Increasing redness or severe swelling of the breast may indicate infection. Contact a midwife.',
  alert_bf_lump_title: 'Painful breast lump',
  alert_bf_lump_msg: 'A painful lump in the breast requires urgent medical evaluation.',
  alert_bf_refuse_title: 'Baby refusing to breastfeed',
  alert_bf_refuse_msg: 'If the baby consistently refuses to breastfeed, consult a specialist.',
  alert_bf_weight_title: 'Baby weight loss',
  alert_bf_weight_msg: 'Baby weight loss or insufficient gain may require a breastfeeding assessment.',
  alert_epis_title: 'Episiotomy warning signs',
  alert_epis_msg: 'Increasing redness, foul-smelling discharge, fever > 38°C, wound opening — consult your doctor immediately.',
  alert_sx_pain_title: 'Persistent pain during intercourse',
  alert_sx_pain_msg: 'Persistent pain during sexual intercourse needs specialist consultation.',
  alert_ppd_title: 'Postpartum depression',
  alert_ppd_msg: 'Deep sadness or loss of interest for more than two weeks needs professional follow-up.',
  alert_action_bf: 'Open breastfeeding guide',
  alert_action_sx: 'Open care guide',
  alert_action_eval: 'Start assessment',
  alerts_medical_intro: 'Important medical alerts to watch for. Consult a specialist if any of these signs appear.',

  // Newborn module
  nb_module_title: 'Newborn Care Guide',
  nb_module_desc: 'Complete newborn care guide',
  nb_title: 'Newborn Care',
  nb_subtitle: 'Guide for newborn care',
  nb_tab_guide: 'Guide',
  nb_tab_myths: 'Myths',
  nb_myths_title: 'Newborn Myths & Facts',
  nb_myths_desc: 'Tap each card to discover the truth',

  // Myths module
  my_module_title: 'Myths & Facts',
  my_module_desc: 'All common myths with scientific correction',
  my_title: 'Myths & Facts',
  my_subtitle: '20 common myths with scientific truth',
  my_tap_hint: 'Tap any card to discover the truth',
  my_footer: 'Information based on WHO recommendations and clinical practices.',

  // Baby Age Widget
  baby_title: 'Baby Age',
  baby_enter_info: 'Enter birth date and time',
  baby_date: 'Birth Date',
  baby_time: 'Birth Time',
  baby_save: 'Save',
  baby_age_title: 'Your Baby\'s Age',
  baby_months: 'Month',
  baby_days: 'Day',
  baby_hours: 'Hour',
  baby_minutes: 'Min',
  baby_newborn_msg: 'Congratulations! Your baby is a newborn ❤️',
  baby_weeks_old: 'Baby is {n} weeks old',
}

};

// ── Translation function ──
function t(key, params = {}) {
  let text = translations[currentLang]?.[key] || translations.fr[key] || key;
  Object.entries(params).forEach(([k, v]) => {
    text = text.replace(`{${k}}`, v);
  });
  return text;
}

// ── Switch language ──
function switchLang(lang) {
  if (!LANGS[lang]) return;
  currentLang = lang;
  localStorage.setItem('nf_lang', lang);

  // Set direction
  const dir = LANGS[lang].dir;
  document.documentElement.setAttribute('dir', dir);
  document.documentElement.setAttribute('lang', lang);
  document.body.classList.toggle('rtl', dir === 'rtl');

  // Update all static i18n elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = t(key);
    } else {
      el.textContent = t(key);
    }
  });

  // Update placeholder-specific i18n
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.dataset.i18nPlaceholder);
  });

  // Refresh current screen
  const screen = state.currentScreen;
  if (screen === 'auth') {
    if (state.authenticated) navigateTo('home');
    else showLogin();
  } else {
    navigateTo(screen);
  }
}

// ── Language Selector UI ──
function showLangSelector() {
  const overlay = document.createElement('div');
  overlay.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,0.4);z-index:200;display:flex;align-items:center;justify-content:center;animation:fadeIn 0.2s ease;';
  overlay.onclick = (e) => { if (e.target === overlay) overlay.remove(); };

  const modal = document.createElement('div');
  modal.style.cssText = 'background:var(--surface);border-radius:var(--radius-2xl);padding:var(--space-2xl);width:calc(100% - 40px);max-width:320px;box-shadow:var(--shadow-elevated);';
  modal.innerHTML = `
    <h3 style="font-size:18px;font-weight:600;margin-bottom:var(--space-xl);text-align:center;">
      <span class="material-symbols-outlined" style="vertical-align:middle;margin-right:8px;">translate</span>
      ${t('prof_lang')}
    </h3>
    ${Object.entries(LANGS).map(([code, info]) => `
      <button onclick="switchLang('${code}');this.closest('[style*=fixed]').remove();"
        style="width:100%;display:flex;align-items:center;gap:var(--space-lg);padding:var(--space-lg);border-radius:var(--radius-xl);margin-bottom:var(--space-sm);
        background:${currentLang===code?'var(--primary-fixed)':'var(--surface-container-low)'};
        border:2px solid ${currentLang===code?'var(--primary)':'transparent'};
        cursor:pointer;transition:all 0.15s;font-family:inherit;font-size:16px;">
        <span style="font-size:28px;">${info.flag}</span>
        <span style="font-weight:${currentLang===code?'700':'500'};color:${currentLang===code?'var(--primary)':'var(--on-surface)'};">${info.label}</span>
        ${currentLang===code?'<span class="material-symbols-outlined text-primary" style="margin-left:auto;">check_circle</span>':''}
      </button>
    `).join('')}
  `;
  overlay.appendChild(modal);
  document.body.appendChild(overlay);
}
