/* ============================================================
   NurtureFlow — Internationalization (i18n)
   Français 🇫🇷 | العربية 🇸🇦 | English 🇬🇧
   ============================================================ */

const LANGS = {
  fr: { label: 'Français', flag: '🇫🇷', dir: 'ltr' },
  ar: { label: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  en: { label: 'English', flag: '🇬🇧', dir: 'ltr' }
};

let currentLang = localStorage.getItem('nf_lang') || 'fr';

// ── Translation dictionaries ──
const translations = {

// ═══════════════════════════════════════
//  FRENCH
// ═══════════════════════════════════════
fr: {
  // App
  app_name: 'NurtureFlow',
  app_tagline: 'De la conjugalité à la parentalité',

  // Auth
  auth_email: 'Email',
  auth_password: 'Mot de passe',
  auth_login: 'Se connecter',
  auth_no_account: 'Pas encore de compte ?',
  auth_create_account: 'Créer un compte couple',
  auth_create_title: 'Créer votre espace couple',
  auth_partner1: 'PARTENAIRE 1',
  auth_partner2: 'PARTENAIRE 2',
  auth_couple_info: 'INFORMATIONS COUPLE',
  auth_security: 'SÉCURITÉ',
  auth_firstname: 'Prénom',
  auth_age: 'Âge',
  auth_woman: 'Femme',
  auth_man: 'Homme',
  auth_marriage_duration: 'Durée du mariage (ex: 3 ans)',
  auth_baby_age: 'Âge du bébé (ex: 4 mois)',
  auth_password_min: 'Mot de passe (min 4 caractères)',
  auth_password_confirm: 'Confirmer le mot de passe',
  auth_create_btn: 'Créer le compte',
  auth_fill_all: 'Veuillez remplir tous les champs',
  auth_pwd_mismatch: 'Les mots de passe ne correspondent pas',
  auth_required: 'Nom, email et mot de passe sont obligatoires',

  // Navigation
  nav_home: 'Home',
  nav_results: 'Résultats',
  nav_library: 'Bibliothèque',
  nav_profile: 'Profil',

  // Drawer
  drawer_home: 'Accueil',
  drawer_evaluations: 'Évaluations',
  drawer_plan: 'Plan Personnalisé',
  drawer_checkup: 'Couple Check-Up',
  drawer_daily: 'Suivi quotidien',
  drawer_alerts: 'Alertes',
  drawer_sage_femme: 'Assistant Sage-Femme',
  drawer_library: 'Bibliothèque',
  drawer_settings: 'Paramètres',
  drawer_admin: 'Admin Dashboard',
  drawer_new_couple: 'Nouveau Couple',
  drawer_logout: 'Déconnexion',
  drawer_welcome: 'Bienvenue',
  drawer_couple_since: 'Couple depuis',

  // Home
  home_hello: 'Bonjour',
  home_ready: 'Prête pour votre accompagnement ?',
  home_global_progress: 'Progression globale',
  home_evals_completed: 'évaluations complétées',
  home_tip_of_day: 'Conseil du jour',
  home_tip_title: 'Maintenir la connexion émotionnelle',
  home_tip_desc: 'Les petits rituels quotidiens renforcent votre lien.',
  home_evaluations: 'AUTO-ÉVALUATIONS',
  home_psycho: 'Psychologique',
  home_conjugal: 'Conjugale',
  home_sexual: 'Sexuelle',
  home_first_eval: 'Première Évaluation',
  home_first_eval_desc: 'Commencez votre première évaluation pour découvrir votre profil.',
  home_last_eval: 'Dernière Évaluation',
  home_daily_tracking: 'Suivi Quotidien',
  home_midwife: 'Sage-Femme',
  home_score: 'Score',

  // Questionnaire
  q_previous: 'Précédent',
  q_next: 'Suivant',
  q_finish: 'Terminer',
  q_question: 'Question',
  q_never: 'Jamais',
  q_rarely: 'Rarement',
  q_sometimes: 'Parfois',
  q_often: 'Souvent',
  q_always: 'Toujours',

  // Questionnaire titles
  qt_psycho: 'Bien-être Psychologique',
  qt_conjugal: 'Relation Conjugale',
  qt_sexual: 'Vie Intime Post-Partum',

  // Questionnaire questions — Psycho
  qp1: 'Comment évaluez-vous votre niveau de stress cette semaine ?',
  qp1h: 'Pensez aux moments de tension ou d\'inquiétude.',
  qp2: 'Avez-vous ressenti de la fatigue excessive ces derniers jours ?',
  qp2h: 'Fatigue physique et/ou mentale liée à la parentalité.',
  qp3: 'Comment décririez-vous votre humeur générale ?',
  qp3h: 'Réfléchissez à votre état émotionnel global.',
  qp4: 'Vous sentez-vous anxieux(se) face aux responsabilités parentales ?',
  qp4h: 'L\'inquiétude liée à votre rôle de parent.',
  qp5: 'Arrivez-vous à vous adapter aux changements depuis l\'arrivée de bébé ?',
  qp5h: 'Votre capacité à gérer la nouvelle routine.',
  qp6: 'Avez-vous eu des moments de découragement ?',
  qp6h: 'Sentiment de ne pas y arriver.',
  qp7: 'Vous accordez-vous du temps pour vous-même ?',
  qp7h: 'Moments de détente, loisirs, repos.',
  qp8: 'Dormez-vous suffisamment pour vous sentir reposé(e) ?',
  qp8h: 'Qualité et durée de votre sommeil.',
  qp9: 'Avez-vous le sentiment de contrôler votre quotidien ?',
  qp9h: 'Sentiment de maîtrise sur votre vie.',
  qp10: 'Vous sentez-vous soutenu(e) émotionnellement ?',
  qp10h: 'Soutien famille, amis, partenaire.',

  // Questionnaire questions — Conjugal
  qc1: 'Comment évaluez-vous votre communication avec votre partenaire ?',
  qc1h: 'Vos échanges au cours des 7 derniers jours.',
  qc2: 'Vous sentez-vous soutenu(e) par votre partenaire ?',
  qc2h: 'Soutien pratique et émotionnel.',
  qc3: 'Avez-vous vécu des conflits ou des désaccords ?',
  qc3h: 'Tensions, disputes, malentendus.',
  qc4: 'Êtes-vous satisfait(e) de votre relation de couple ?',
  qc4h: 'Satisfaction globale.',
  qc5: 'Avez-vous passé du temps de qualité ensemble ?',
  qc5h: 'Moments partagés sans obligations parentales.',
  qc6: 'Partagez-vous équitablement les tâches parentales ?',
  qc6h: 'Répartition des soins et tâches.',
  qc7: 'Exprimez-vous facilement vos besoins ?',
  qc7h: 'Communication ouverte sur vos attentes.',
  qc8: 'Vous sentez-vous écouté(e) par votre partenaire ?',
  qc8h: 'Attention et compréhension.',
  qc9: 'Avez-vous partagé des moments de joie ensemble ?',
  qc9h: 'Complicité et bonheur partagé.',
  qc10: 'Ressentez-vous de la complicité avec votre partenaire ?',
  qc10h: 'Connexion et unité.',

  // Questionnaire questions — Sexual
  qs1: 'Ressentez-vous du désir pour votre partenaire ?',
  qs1h: 'Attraction et envie d\'intimité.',
  qs2: 'Êtes-vous satisfait(e) de votre vie intime actuelle ?',
  qs2h: 'Niveau de satisfaction.',
  qs3: 'Communiquez-vous ouvertement sur votre sexualité ?',
  qs3h: 'Capacité à aborder le sujet.',
  qs4: 'Avez-vous rencontré des difficultés physiques ?',
  qs4h: 'Douleurs, inconfort, changements.',
  qs5: 'Ressentez-vous de l\'appréhension ou de la douleur ?',
  qs5h: 'Craintes liées à la reprise.',
  qs6: 'Vous sentez-vous à l\'aise avec votre corps ?',
  qs6h: 'Image corporelle post-partum.',
  qs7: 'Avez-vous eu des moments d\'intimité non sexuelle ?',
  qs7h: 'Câlins, caresses, tendresse.',
  qs8: 'La fatigue affecte-t-elle votre vie intime ?',
  qs8h: 'Impact de l\'épuisement.',
  qs9: 'Avez-vous discuté de contraception ?',
  qs9h: 'Communication sur la prévention.',
  qs10: 'Vous sentez-vous désirable ?',
  qs10h: 'Sentiment d\'être attirant(e).',

  // Results
  res_global: 'Global',
  res_global_index: 'Indice Global d\'Équilibre',
  res_analysis: 'Analyse Détaillée',
  res_psycho: 'Psychologique',
  res_conjugal: 'Conjugal',
  res_sexual: 'Sexuel',
  res_explanation: 'Explication personnalisée',
  res_first_eval_msg: 'Complétez vos premières évaluations pour une analyse personnalisée.',
  res_excellent: 'Excellent',
  res_bon: 'Bon',
  res_moyen: 'Moyen',
  res_faible: 'Faible',
  res_orientation: 'Orientation recommandée',
  res_consult: 'Score {types} faible. Consultez un professionnel.',

  // Library
  lib_title: 'Bibliothèque',
  lib_subtitle: 'Conseils d\'experts pour chaque étape.',
  lib_search: 'Rechercher un article...',
  lib_timeline: 'TIMELINE POST-PARTUM',
  lib_all: 'Tous',
  lib_mental_health: 'Santé Mentale',
  lib_sexuality: 'Sexualité',
  lib_couple_life: 'Vie de Couple',
  lib_breastfeeding: 'Allaitement',
  lib_featured: 'Article Vedette',
  lib_postpartum_title: 'Le post-partum immédiat',
  lib_postpartum_desc: 'Comprendre les changements des premières 48 heures.',
  lib_read_more: 'Lire plus →',
  lib_breathing: 'Respiration post-natale',
  lib_sleep: 'Gérer le manque de sommeil',
  lib_communication: 'Communication dans le couple',
  lib_comm_desc: 'Maintenir le lien après l\'arrivée de bébé.',
  lib_partner_role: 'Le rôle du partenaire',
  lib_intimacy: 'Retrouver son intimité',
  lib_content_period: 'CONTENU',
  lib_months: 'MOIS',

  // Profile
  prof_info: 'INFORMATIONS',
  prof_age: 'Âge',
  prof_sex: 'Sexe',
  prof_marriage: 'Durée du mariage',
  prof_baby: 'Âge du bébé',
  prof_partner2: 'Partenaire 2',
  prof_not_set: 'Non renseigné',
  prof_stats: 'STATISTIQUES',
  prof_evaluations: 'Évaluations',
  prof_articles: 'Articles',
  prof_streak: 'Jours suivi',
  prof_settings: 'PARAMÈTRES',
  prof_notif: 'Notifications',
  prof_lang: 'Langue',
  prof_version: 'Version',

  // Sage-femme
  sf_title: 'Assistant Sage-Femme',
  sf_subtitle: 'Conseils professionnels post-partum',
  sf_all: 'Tous',
  sf_postpartum: 'Post-partum',
  sf_breastfeeding: 'Allaitement',
  sf_contraception: 'Contraception',
  sf_sexuality: 'Sexualité',
  sf_alerts: '⚠️ Alertes',

  // Sage-femme tips
  sft1_title: 'Récupération post-partum',
  sft1_text: 'Les premières semaines sont cruciales. Accordez-vous du repos, écoutez votre corps. Les lochies durent 4 à 6 semaines. Consultez si fièvre ou douleurs intenses.',
  sft2_title: 'Allaitement maternel',
  sft2_text: 'Mise au sein dans la première heure. Allaitez à la demande. Si douleurs, vérifiez la position et la prise du sein. Demandez l\'aide d\'une consultante.',
  sft3_title: 'Contraception post-partum',
  sft3_text: 'Reprise possible dès 21 jours. Options : DIU, pilule progestative, implant. L\'allaitement exclusif n\'est PAS une contraception fiable.',
  sft4_title: 'Reprise de la sexualité',
  sft4_text: 'Pas de délai obligatoire. Sécheresse vaginale normale. Utilisez un lubrifiant. Communiquez avec votre partenaire.',
  sft5_title: 'Signes d\'alerte ⚠️',
  sft5_text: 'Consultez immédiatement si : fièvre >38°C, saignements abondants, douleur intense, tristesse >2 semaines, pensées sombres, difficultés d\'attachement au bébé.',
  sft6_title: 'Baby blues vs Dépression',
  sft6_text: 'Baby blues (J3-J10) : normal, passager. Dépression post-partum (>2 semaines) : tristesse profonde, perte d\'intérêt. Parlez-en à un professionnel.',
  sft7_title: 'Engorgement mammaire',
  sft7_text: 'Fréquent vers J3-J5. Compresses chaudes avant tétée, froides après. Massage sous la douche. Allaitez fréquemment.',
  sft8_title: 'Rééducation périnéale',
  sft8_text: 'Recommandée après tout accouchement, dès 6-8 semaines. Prévient l\'incontinence et améliore le confort intime.',

  // Daily tracking
  daily_title: 'Comment vous sentez-vous ?',
  daily_subtitle: 'Enregistrez votre humeur quotidienne.',
  daily_mood: 'HUMEUR DU JOUR',
  daily_exhausted: 'Épuisé',
  daily_sad: 'Triste',
  daily_neutral: 'Neutre',
  daily_good: 'Bien',
  daily_great: 'Super',
  daily_stress: 'Niveau de stress',
  daily_conjugal: 'Satisfaction conjugale',
  daily_intimate: 'Satisfaction intime',
  daily_save: 'Enregistrer mon suivi',
  daily_saved: 'Enregistré !',
  daily_evolution: 'Évolution récente',
  daily_satisfaction: 'Satisfaction',
  daily_stress_label: 'Stress',
  daily_history: 'Historique récent',
  daily_no_entries: 'Aucune entrée. Commencez votre suivi ci-dessus !',

  // Plan
  plan_title: 'Plan Personnalisé',
  plan_subtitle: 'Exercices et conseils adaptés à vos scores',
  plan_days: 'jours',
  plan_focus: 'Axes prioritaires',
  plan_focus_desc: 'Basé sur vos scores, nous recommandons de vous concentrer sur :',
  plan_activities: 'ACTIVITÉS',
  plan_completed: 'activités complétées',
  plan_psycho_focus: 'bien-être psychologique',
  plan_comm_focus: 'communication conjugale',
  plan_pp_focus: 'accompagnement post-partum',

  // Check-up
  checkup_monthly: 'BILAN MENSUEL',
  checkup_global_score: 'Score Global',
  checkup_by_dimension: 'SCORES PAR DIMENSION',
  checkup_evolution: 'Évolution des scores',
  checkup_recommendations: 'RECOMMANDATIONS',
  checkup_start_plan: 'Commencer un Plan Personnalisé',
  checkup_see_results: 'Voir les résultats détaillés',
  checkup_trend_up: '↑ En hausse',
  checkup_trend_down: '↓ En baisse',
  checkup_trend_stable: '= Stable',
  checkup_trend_new: 'Nouveau',

  // Alerts
  alerts_title: 'Alertes & Orientation',
  alerts_subtitle: 'Suivi intelligent de votre bien-être',
  alerts_all_good: 'Tout va bien ! ✨',
  alerts_none: 'Aucune alerte pour le moment. Continuez votre suivi régulier.',
  alerts_back_home: 'Retour à l\'accueil',
  alerts_important: 'Rappel important',
  alerts_disclaimer: 'NurtureFlow est un outil de prévention et de sensibilisation. En cas de détresse, contactez immédiatement un professionnel de santé ou le 3114 (numéro national de prévention du suicide).',
  alerts_alert: 'alerte',
  alerts_alerts: 'alertes',
  alerts_critical: 'critique',
  alerts_criticals: 'critiques',
  alerts_warning: 'avertissement',
  alerts_warnings: 'avertissements',

  // Admin
  admin_title: 'Administration NurtureFlow',
  admin_subtitle: 'Vue d\'ensemble de la plateforme',
  admin_dashboard: 'TABLEAU DE BORD',
  admin_couples: 'Couples inscrits',
  admin_active: 'Actifs (7j)',
  admin_evals: 'Évaluations',
  admin_daily: 'Suivis quotidiens',
  admin_avg_scores: 'Scores Moyens Globaux',
  admin_score_distrib: 'Distribution des Scores',
  admin_evals_by_type: 'Évaluations par Type',
  admin_recent_couples: 'COUPLES RÉCENTS',
  admin_restricted: 'Accès restreint',
  admin_restricted_msg: 'Cette section est réservée à l\'administrateur.',
  admin_info: 'INFORMATIONS',
  admin_return: 'Retour',

  // New couple
  nc_title: 'Créer un nouveau couple',
  nc_subtitle: 'Enregistrer un couple dans la base',
  nc_create: 'Créer le couple',
  nc_creating: 'Création en cours...',
  nc_success: 'Couple créé avec succès !',
  nc_created: 'Couple créé !',

  // Misc
  misc_just_now: 'À l\'instant',
  misc_ago_min: 'Il y a {n} min',
  misc_ago_hours: 'Il y a {n}h',
  misc_yesterday: 'Hier',
  misc_ago_days: 'Il y a {n} jours',
  misc_loading: 'Chargement...',
  misc_error: 'Erreur',
  misc_back: 'Retour',
  misc_min_read: 'min de lecture',
  misc_period: 'Période',
  misc_back_library: 'Retour à la bibliothèque',
  misc_video: 'Vidéo',
  misc_guide: 'Guide',
  misc_article: 'Article',
},

// ═══════════════════════════════════════
//  ARABIC
// ═══════════════════════════════════════
ar: {
  app_name: 'NurtureFlow',
  app_tagline: 'من الحياة الزوجية إلى الأبوة',

  auth_email: 'البريد الإلكتروني',
  auth_password: 'كلمة المرور',
  auth_login: 'تسجيل الدخول',
  auth_no_account: 'ليس لديك حساب؟',
  auth_create_account: 'إنشاء حساب للزوجين',
  auth_create_title: 'إنشاء حسابكم كزوجين',
  auth_partner1: 'الشريك 1',
  auth_partner2: 'الشريك 2',
  auth_couple_info: 'معلومات الزوجين',
  auth_security: 'الأمان',
  auth_firstname: 'الاسم الأول',
  auth_age: 'العمر',
  auth_woman: 'أنثى',
  auth_man: 'ذكر',
  auth_marriage_duration: 'مدة الزواج (مثال: 3 سنوات)',
  auth_baby_age: 'عمر الطفل (مثال: 4 أشهر)',
  auth_password_min: 'كلمة المرور (4 أحرف على الأقل)',
  auth_password_confirm: 'تأكيد كلمة المرور',
  auth_create_btn: 'إنشاء الحساب',
  auth_fill_all: 'يرجى ملء جميع الحقول',
  auth_pwd_mismatch: 'كلمتا المرور غير متطابقتين',
  auth_required: 'الاسم والبريد وكلمة المرور مطلوبة',

  nav_home: 'الرئيسية',
  nav_results: 'النتائج',
  nav_library: 'المكتبة',
  nav_profile: 'الملف',

  drawer_home: 'الرئيسية',
  drawer_evaluations: 'التقييمات',
  drawer_plan: 'خطة مخصصة',
  drawer_checkup: 'فحص الزوجين',
  drawer_daily: 'المتابعة اليومية',
  drawer_alerts: 'التنبيهات',
  drawer_sage_femme: 'مساعدة القابلة',
  drawer_library: 'المكتبة',
  drawer_settings: 'الإعدادات',
  drawer_admin: 'لوحة الإدارة',
  drawer_new_couple: 'زوجان جديدان',
  drawer_logout: 'تسجيل الخروج',
  drawer_welcome: 'مرحباً',
  drawer_couple_since: 'متزوجان منذ',

  home_hello: 'مرحباً',
  home_ready: 'هل أنتِ مستعدة للمرافقة؟',
  home_global_progress: 'التقدم العام',
  home_evals_completed: 'تقييمات مكتملة',
  home_tip_of_day: 'نصيحة اليوم',
  home_tip_title: 'الحفاظ على الترابط العاطفي',
  home_tip_desc: 'الطقوس اليومية الصغيرة تقوي رابطكم.',
  home_evaluations: 'التقييمات الذاتية',
  home_psycho: 'نفسي',
  home_conjugal: 'زوجي',
  home_sexual: 'جنسي',
  home_first_eval: 'التقييم الأول',
  home_first_eval_desc: 'ابدأي تقييمك الأول لاكتشاف ملفك الشخصي.',
  home_last_eval: 'آخر تقييم',
  home_daily_tracking: 'المتابعة اليومية',
  home_midwife: 'القابلة',
  home_score: 'النتيجة',

  q_previous: 'السابق',
  q_next: 'التالي',
  q_finish: 'إنهاء',
  q_question: 'السؤال',
  q_never: 'أبداً',
  q_rarely: 'نادراً',
  q_sometimes: 'أحياناً',
  q_often: 'غالباً',
  q_always: 'دائماً',

  qt_psycho: 'الرفاه النفسي',
  qt_conjugal: 'العلاقة الزوجية',
  qt_sexual: 'الحياة الحميمية بعد الولادة',

  qp1: 'كيف تقيّمين مستوى التوتر لديك هذا الأسبوع؟',
  qp1h: 'فكّري في لحظات التوتر والقلق.',
  qp2: 'هل شعرتِ بإرهاق شديد في الأيام الأخيرة؟',
  qp2h: 'إرهاق جسدي و/أو نفسي مرتبط بالأمومة.',
  qp3: 'كيف تصفين مزاجك العام؟',
  qp3h: 'فكّري في حالتك العاطفية الشاملة.',
  qp4: 'هل تشعرين بالقلق تجاه مسؤوليات الأمومة؟',
  qp4h: 'القلق المتعلق بدورك كأم.',
  qp5: 'هل تستطيعين التأقلم مع التغييرات منذ وصول الطفل؟',
  qp5h: 'قدرتك على إدارة الروتين الجديد.',
  qp6: 'هل مررتِ بلحظات إحباط؟',
  qp6h: 'الشعور بعدم القدرة على التحمل.',
  qp7: 'هل تخصصين وقتاً لنفسك؟',
  qp7h: 'لحظات الراحة والترفيه.',
  qp8: 'هل تنامين بما يكفي لتشعري بالراحة؟',
  qp8h: 'جودة ومدة نومك.',
  qp9: 'هل تشعرين بالسيطرة على حياتك اليومية؟',
  qp9h: 'الشعور بالتحكم في حياتك.',
  qp10: 'هل تشعرين بالدعم العاطفي؟',
  qp10h: 'دعم العائلة والأصدقاء والشريك.',

  qc1: 'كيف تقيّمين تواصلك مع شريكك؟',
  qc1h: 'حواراتكم خلال الأيام السبعة الأخيرة.',
  qc2: 'هل تشعرين بدعم شريكك لك؟',
  qc2h: 'الدعم العملي والعاطفي.',
  qc3: 'هل مررتم بنزاعات أو خلافات؟',
  qc3h: 'توترات، نقاشات، سوء تفاهم.',
  qc4: 'هل أنتِ راضية عن علاقتكما كزوجين؟',
  qc4h: 'الرضا العام.',
  qc5: 'هل قضيتما وقتاً نوعياً معاً؟',
  qc5h: 'لحظات مشتركة بدون واجبات الأبوة.',
  qc6: 'هل تتقاسمون المهام الأبوية بالتساوي؟',
  qc6h: 'توزيع الرعاية والمهام.',
  qc7: 'هل تعبّرين بسهولة عن احتياجاتك؟',
  qc7h: 'التواصل المفتوح حول توقعاتك.',
  qc8: 'هل تشعرين أن شريكك يستمع إليك؟',
  qc8h: 'الاهتمام والتفهم.',
  qc9: 'هل شاركتما لحظات فرح معاً؟',
  qc9h: 'التواطؤ والسعادة المشتركة.',
  qc10: 'هل تشعرين بالتواطؤ مع شريكك؟',
  qc10h: 'الترابط والوحدة.',

  qs1: 'هل تشعرين بالرغبة تجاه شريكك؟',
  qs1h: 'الانجذاب والرغبة في العلاقة الحميمية.',
  qs2: 'هل أنتِ راضية عن حياتكم الحميمية الحالية؟',
  qs2h: 'مستوى الرضا.',
  qs3: 'هل تتحدثون بصراحة عن حياتكم الجنسية؟',
  qs3h: 'القدرة على طرح الموضوع.',
  qs4: 'هل واجهتِ صعوبات جسدية؟',
  qs4h: 'آلام، عدم راحة، تغيرات.',
  qs5: 'هل تشعرين بالتخوف أو الألم؟',
  qs5h: 'مخاوف مرتبطة بالعودة.',
  qs6: 'هل تشعرين بالراحة مع جسمك؟',
  qs6h: 'صورة الجسم بعد الولادة.',
  qs7: 'هل مررتم بلحظات حميمية غير جنسية؟',
  qs7h: 'عناق، ملاطفة، حنان.',
  qs8: 'هل يؤثر التعب على حياتكم الحميمية؟',
  qs8h: 'تأثير الإرهاق.',
  qs9: 'هل ناقشتم موضوع منع الحمل؟',
  qs9h: 'التواصل حول الوقاية.',
  qs10: 'هل تشعرين أنك مرغوبة؟',
  qs10h: 'الشعور بالجاذبية.',

  res_global: 'عام',
  res_global_index: 'المؤشر العام لتوازن الزوجين',
  res_analysis: 'تحليل مفصل',
  res_psycho: 'نفسي',
  res_conjugal: 'زوجي',
  res_sexual: 'جنسي',
  res_explanation: 'شرح مخصص',
  res_first_eval_msg: 'أكملي تقييماتك الأولى للحصول على تحليل مخصص.',
  res_excellent: 'ممتاز',
  res_bon: 'جيد',
  res_moyen: 'متوسط',
  res_faible: 'ضعيف',
  res_orientation: 'توجيه موصى به',
  res_consult: 'نتيجة {types} ضعيفة. استشيري متخصصاً.',

  lib_title: 'المكتبة',
  lib_subtitle: 'نصائح الخبراء لكل مرحلة.',
  lib_search: 'البحث عن مقال...',
  lib_timeline: 'الجدول الزمني لما بعد الولادة',
  lib_all: 'الكل',
  lib_mental_health: 'الصحة النفسية',
  lib_sexuality: 'الحياة الجنسية',
  lib_couple_life: 'حياة الزوجين',
  lib_breastfeeding: 'الرضاعة',
  lib_featured: 'مقال مميز',
  lib_postpartum_title: 'ما بعد الولادة المباشر',
  lib_postpartum_desc: 'فهم تغيرات الساعات الـ 48 الأولى.',
  lib_read_more: 'اقرأي المزيد ←',
  lib_breathing: 'تمارين التنفس بعد الولادة',
  lib_sleep: 'التعامل مع قلة النوم',
  lib_communication: 'التواصل في الزوجين',
  lib_comm_desc: 'الحفاظ على الرابط بعد وصول الطفل.',
  lib_partner_role: 'دور الشريك',
  lib_intimacy: 'استعادة العلاقة الحميمية',
  lib_content_period: 'محتوى',
  lib_months: 'أشهر',

  prof_info: 'المعلومات',
  prof_age: 'العمر',
  prof_sex: 'الجنس',
  prof_marriage: 'مدة الزواج',
  prof_baby: 'عمر الطفل',
  prof_partner2: 'الشريك 2',
  prof_not_set: 'غير محدد',
  prof_stats: 'الإحصائيات',
  prof_evaluations: 'التقييمات',
  prof_articles: 'المقالات',
  prof_streak: 'أيام المتابعة',
  prof_settings: 'الإعدادات',
  prof_notif: 'الإشعارات',
  prof_lang: 'اللغة',
  prof_version: 'الإصدار',

  sf_title: 'مساعدة القابلة',
  sf_subtitle: 'نصائح مهنية لما بعد الولادة',
  sf_all: 'الكل',
  sf_postpartum: 'ما بعد الولادة',
  sf_breastfeeding: 'الرضاعة',
  sf_contraception: 'منع الحمل',
  sf_sexuality: 'الحياة الجنسية',
  sf_alerts: '⚠️ تنبيهات',

  sft1_title: 'التعافي بعد الولادة',
  sft1_text: 'الأسابيع الأولى حاسمة. خذي قسطاً من الراحة واستمعي لجسمك. النزيف يستمر 4-6 أسابيع. استشيري في حالة الحمى أو الآلام الشديدة.',
  sft2_title: 'الرضاعة الطبيعية',
  sft2_text: 'الإرضاع في الساعة الأولى. أرضعي عند الطلب. في حالة الألم، تحققي من وضعية الإرضاع. اطلبي مساعدة مستشارة الرضاعة.',
  sft3_title: 'منع الحمل بعد الولادة',
  sft3_text: 'يمكن العودة بعد 21 يوماً. الخيارات: اللولب، حبوب البروجسترون، الغرسة. الرضاعة الحصرية ليست وسيلة منع حمل موثوقة.',
  sft4_title: 'استئناف العلاقة الجنسية',
  sft4_text: 'لا يوجد موعد إلزامي. الجفاف المهبلي طبيعي. استخدمي مزلقاً. تحدثي مع شريكك.',
  sft5_title: 'علامات إنذار ⚠️',
  sft5_text: 'استشيري فوراً إذا: حمى >38 درجة، نزيف غزير، ألم شديد، حزن >أسبوعين، أفكار مظلمة، صعوبة في التعلق بالطفل.',
  sft6_title: 'كآبة الأمومة مقابل الاكتئاب',
  sft6_text: 'كآبة الأمومة (ي3-ي10): طبيعية وعابرة. اكتئاب ما بعد الولادة (>أسبوعين): حزن عميق، فقدان الاهتمام. تحدثي مع متخصص.',
  sft7_title: 'احتقان الثدي',
  sft7_text: 'شائع في ي3-ي5. كمادات دافئة قبل الرضاعة وباردة بعدها. تدليك تحت الدوش. أرضعي بشكل متكرر.',
  sft8_title: 'إعادة تأهيل العجان',
  sft8_text: 'موصى بها بعد أي ولادة، بدءاً من 6-8 أسابيع. تمنع السلس وتحسن الراحة الحميمية.',

  daily_title: 'كيف تشعرين؟',
  daily_subtitle: 'سجلي مزاجك اليومي.',
  daily_mood: 'مزاج اليوم',
  daily_exhausted: 'منهكة',
  daily_sad: 'حزينة',
  daily_neutral: 'عادي',
  daily_good: 'جيدة',
  daily_great: 'رائعة',
  daily_stress: 'مستوى التوتر',
  daily_conjugal: 'الرضا الزوجي',
  daily_intimate: 'الرضا الحميمي',
  daily_save: 'حفظ المتابعة',
  daily_saved: 'تم الحفظ!',
  daily_evolution: 'التطور الأخير',
  daily_satisfaction: 'الرضا',
  daily_stress_label: 'التوتر',
  daily_history: 'السجل الأخير',
  daily_no_entries: 'لا توجد إدخالات. ابدأي المتابعة أعلاه!',

  plan_title: 'خطة مخصصة',
  plan_subtitle: 'تمارين ونصائح مكيّفة حسب نتائجك',
  plan_days: 'يوم',
  plan_focus: 'المحاور ذات الأولوية',
  plan_focus_desc: 'بناءً على نتائجك، نوصي بالتركيز على:',
  plan_activities: 'الأنشطة',
  plan_completed: 'أنشطة مكتملة',
  plan_psycho_focus: 'الرفاه النفسي',
  plan_comm_focus: 'التواصل الزوجي',
  plan_pp_focus: 'مرافقة ما بعد الولادة',

  checkup_monthly: 'تقرير شهري',
  checkup_global_score: 'النتيجة العامة',
  checkup_by_dimension: 'النتائج حسب البعد',
  checkup_evolution: 'تطور النتائج',
  checkup_recommendations: 'التوصيات',
  checkup_start_plan: 'بدء خطة مخصصة',
  checkup_see_results: 'عرض النتائج المفصلة',
  checkup_trend_up: '↑ في ارتفاع',
  checkup_trend_down: '↓ في انخفاض',
  checkup_trend_stable: '= مستقر',
  checkup_trend_new: 'جديد',

  alerts_title: 'التنبيهات والتوجيه',
  alerts_subtitle: 'متابعة ذكية لصحتك',
  alerts_all_good: 'كل شيء على ما يرام! ✨',
  alerts_none: 'لا توجد تنبيهات حالياً. تابعي المتابعة المنتظمة.',
  alerts_back_home: 'العودة للرئيسية',
  alerts_important: 'تذكير مهم',
  alerts_disclaimer: 'NurtureFlow هو أداة للوقاية والتوعية. في حالة الضيق، اتصلي فوراً بمتخصص صحي أو بالرقم 3114.',
  alerts_alert: 'تنبيه',
  alerts_alerts: 'تنبيهات',
  alerts_critical: 'حرج',
  alerts_criticals: 'حرجة',
  alerts_warning: 'تحذير',
  alerts_warnings: 'تحذيرات',

  admin_title: 'إدارة NurtureFlow',
  admin_subtitle: 'نظرة عامة على المنصة',
  admin_dashboard: 'لوحة التحكم',
  admin_couples: 'أزواج مسجلون',
  admin_active: 'نشطون (7 أيام)',
  admin_evals: 'تقييمات',
  admin_daily: 'متابعات يومية',
  admin_avg_scores: 'متوسط النتائج العامة',
  admin_score_distrib: 'توزيع النتائج',
  admin_evals_by_type: 'التقييمات حسب النوع',
  admin_recent_couples: 'أزواج حديثون',
  admin_restricted: 'وصول مقيد',
  admin_restricted_msg: 'هذا القسم مخصص للمسؤول فقط.',
  admin_info: 'المعلومات',
  admin_return: 'رجوع',

  nc_title: 'إنشاء زوجين جديدين',
  nc_subtitle: 'تسجيل زوجين في القاعدة',
  nc_create: 'إنشاء الزوجين',
  nc_creating: 'جارٍ الإنشاء...',
  nc_success: 'تم إنشاء الزوجين بنجاح!',
  nc_created: 'تم الإنشاء!',

  misc_just_now: 'الآن',
  misc_ago_min: 'منذ {n} دقيقة',
  misc_ago_hours: 'منذ {n} ساعة',
  misc_yesterday: 'أمس',
  misc_ago_days: 'منذ {n} يوم',
  misc_loading: 'جارٍ التحميل...',
  misc_error: 'خطأ',
  misc_back: 'رجوع',
  misc_min_read: 'دقيقة قراءة',
  misc_period: 'الفترة',
  misc_back_library: 'العودة للمكتبة',
  misc_video: 'فيديو',
  misc_guide: 'دليل',
  misc_article: 'مقال',
},

// ═══════════════════════════════════════
//  ENGLISH
// ═══════════════════════════════════════
en: {
  app_name: 'NurtureFlow',
  app_tagline: 'From Couplehood to Parenthood',

  auth_email: 'Email',
  auth_password: 'Password',
  auth_login: 'Sign in',
  auth_no_account: 'Don\'t have an account?',
  auth_create_account: 'Create a couple account',
  auth_create_title: 'Create your couple space',
  auth_partner1: 'PARTNER 1',
  auth_partner2: 'PARTNER 2',
  auth_couple_info: 'COUPLE INFO',
  auth_security: 'SECURITY',
  auth_firstname: 'First name',
  auth_age: 'Age',
  auth_woman: 'Female',
  auth_man: 'Male',
  auth_marriage_duration: 'Marriage duration (e.g. 3 years)',
  auth_baby_age: 'Baby\'s age (e.g. 4 months)',
  auth_password_min: 'Password (min 4 characters)',
  auth_password_confirm: 'Confirm password',
  auth_create_btn: 'Create account',
  auth_fill_all: 'Please fill in all fields',
  auth_pwd_mismatch: 'Passwords do not match',
  auth_required: 'Name, email and password are required',

  nav_home: 'Home',
  nav_results: 'Results',
  nav_library: 'Library',
  nav_profile: 'Profile',

  drawer_home: 'Home',
  drawer_evaluations: 'Evaluations',
  drawer_plan: 'Personal Plan',
  drawer_checkup: 'Couple Check-Up',
  drawer_daily: 'Daily Tracking',
  drawer_alerts: 'Alerts',
  drawer_sage_femme: 'Midwife Assistant',
  drawer_library: 'Library',
  drawer_settings: 'Settings',
  drawer_admin: 'Admin Dashboard',
  drawer_new_couple: 'New Couple',
  drawer_logout: 'Sign out',
  drawer_welcome: 'Welcome',
  drawer_couple_since: 'Couple since',

  home_hello: 'Hello',
  home_ready: 'Ready for your guidance?',
  home_global_progress: 'Overall progress',
  home_evals_completed: 'evaluations completed',
  home_tip_of_day: 'Tip of the day',
  home_tip_title: 'Maintaining emotional connection',
  home_tip_desc: 'Small daily rituals strengthen your bond.',
  home_evaluations: 'SELF-ASSESSMENTS',
  home_psycho: 'Psychological',
  home_conjugal: 'Conjugal',
  home_sexual: 'Sexual',
  home_first_eval: 'First Assessment',
  home_first_eval_desc: 'Start your first assessment to discover your profile.',
  home_last_eval: 'Last Assessment',
  home_daily_tracking: 'Daily Tracking',
  home_midwife: 'Midwife',
  home_score: 'Score',

  q_previous: 'Previous',
  q_next: 'Next',
  q_finish: 'Finish',
  q_question: 'Question',
  q_never: 'Never',
  q_rarely: 'Rarely',
  q_sometimes: 'Sometimes',
  q_often: 'Often',
  q_always: 'Always',

  qt_psycho: 'Psychological Well-being',
  qt_conjugal: 'Conjugal Relationship',
  qt_sexual: 'Postpartum Intimacy',

  qp1: 'How would you rate your stress level this week?',
  qp1h: 'Think about moments of tension or worry.',
  qp2: 'Have you felt excessive fatigue recently?',
  qp2h: 'Physical and/or mental fatigue related to parenthood.',
  qp3: 'How would you describe your general mood?',
  qp3h: 'Think about your overall emotional state.',
  qp4: 'Do you feel anxious about parenting responsibilities?',
  qp4h: 'Worry related to your role as a parent.',
  qp5: 'Are you adapting well to changes since baby arrived?',
  qp5h: 'Your ability to manage the new routine.',
  qp6: 'Have you experienced moments of discouragement?',
  qp6h: 'Feeling unable to cope.',
  qp7: 'Do you take time for yourself?',
  qp7h: 'Moments of relaxation, hobbies, rest.',
  qp8: 'Are you sleeping enough to feel rested?',
  qp8h: 'Quality and duration of your sleep.',
  qp9: 'Do you feel in control of your daily life?',
  qp9h: 'Sense of mastery over your life.',
  qp10: 'Do you feel emotionally supported?',
  qp10h: 'Support from family, friends, partner.',

  qc1: 'How do you rate communication with your partner?',
  qc1h: 'Your exchanges over the past 7 days.',
  qc2: 'Do you feel supported by your partner?',
  qc2h: 'Practical and emotional support.',
  qc3: 'Have you experienced conflicts or disagreements?',
  qc3h: 'Tensions, arguments, misunderstandings.',
  qc4: 'Are you satisfied with your relationship?',
  qc4h: 'Overall satisfaction.',
  qc5: 'Have you spent quality time together?',
  qc5h: 'Shared moments without parental duties.',
  qc6: 'Do you share parenting tasks equally?',
  qc6h: 'Distribution of care and tasks.',
  qc7: 'Can you easily express your needs?',
  qc7h: 'Open communication about your expectations.',
  qc8: 'Do you feel heard by your partner?',
  qc8h: 'Attention and understanding.',
  qc9: 'Have you shared moments of joy together?',
  qc9h: 'Complicity and shared happiness.',
  qc10: 'Do you feel complicity with your partner?',
  qc10h: 'Connection and unity.',

  qs1: 'Do you feel desire for your partner?',
  qs1h: 'Attraction and desire for intimacy.',
  qs2: 'Are you satisfied with your current intimate life?',
  qs2h: 'Level of satisfaction.',
  qs3: 'Do you openly communicate about your sexuality?',
  qs3h: 'Ability to discuss the topic.',
  qs4: 'Have you encountered physical difficulties?',
  qs4h: 'Pain, discomfort, changes.',
  qs5: 'Do you feel apprehension or pain?',
  qs5h: 'Fears about resuming intimacy.',
  qs6: 'Are you comfortable with your body?',
  qs6h: 'Postpartum body image.',
  qs7: 'Have you had non-sexual intimate moments?',
  qs7h: 'Cuddling, caressing, tenderness.',
  qs8: 'Does fatigue affect your intimate life?',
  qs8h: 'Impact of exhaustion.',
  qs9: 'Have you discussed contraception?',
  qs9h: 'Communication about prevention.',
  qs10: 'Do you feel desirable?',
  qs10h: 'Feeling attractive.',

  res_global: 'Global',
  res_global_index: 'Global Couple Balance Index',
  res_analysis: 'Detailed Analysis',
  res_psycho: 'Psychological',
  res_conjugal: 'Conjugal',
  res_sexual: 'Sexual',
  res_explanation: 'Personalized explanation',
  res_first_eval_msg: 'Complete your first assessments for a personalized analysis.',
  res_excellent: 'Excellent',
  res_bon: 'Good',
  res_moyen: 'Average',
  res_faible: 'Low',
  res_orientation: 'Recommended guidance',
  res_consult: '{types} score is low. Consult a professional.',

  lib_title: 'Library',
  lib_subtitle: 'Expert advice for every stage.',
  lib_search: 'Search for an article...',
  lib_timeline: 'POSTPARTUM TIMELINE',
  lib_all: 'All',
  lib_mental_health: 'Mental Health',
  lib_sexuality: 'Sexuality',
  lib_couple_life: 'Couple Life',
  lib_breastfeeding: 'Breastfeeding',
  lib_featured: 'Featured Article',
  lib_postpartum_title: 'The immediate postpartum',
  lib_postpartum_desc: 'Understanding the changes in the first 48 hours.',
  lib_read_more: 'Read more →',
  lib_breathing: 'Postnatal breathing',
  lib_sleep: 'Managing sleep deprivation',
  lib_communication: 'Couple communication',
  lib_comm_desc: 'Maintaining the bond after baby arrives.',
  lib_partner_role: 'The partner\'s role',
  lib_intimacy: 'Rediscovering intimacy',
  lib_content_period: 'CONTENT',
  lib_months: 'MONTHS',

  prof_info: 'INFORMATION',
  prof_age: 'Age',
  prof_sex: 'Gender',
  prof_marriage: 'Marriage duration',
  prof_baby: 'Baby\'s age',
  prof_partner2: 'Partner 2',
  prof_not_set: 'Not specified',
  prof_stats: 'STATISTICS',
  prof_evaluations: 'Evaluations',
  prof_articles: 'Articles',
  prof_streak: 'Days tracked',
  prof_settings: 'SETTINGS',
  prof_notif: 'Notifications',
  prof_lang: 'Language',
  prof_version: 'Version',

  sf_title: 'Midwife Assistant',
  sf_subtitle: 'Professional postpartum advice',
  sf_all: 'All',
  sf_postpartum: 'Postpartum',
  sf_breastfeeding: 'Breastfeeding',
  sf_contraception: 'Contraception',
  sf_sexuality: 'Sexuality',
  sf_alerts: '⚠️ Alerts',

  sft1_title: 'Postpartum recovery',
  sft1_text: 'The first weeks are crucial. Rest and listen to your body. Lochia lasts 4-6 weeks. Consult if fever or severe pain.',
  sft2_title: 'Breastfeeding',
  sft2_text: 'First feeding within the first hour. Feed on demand. If painful, check position and latch. Ask a lactation consultant.',
  sft3_title: 'Postpartum contraception',
  sft3_text: 'Can resume from day 21. Options: IUD, progestogen pill, implant. Exclusive breastfeeding is NOT a reliable contraception.',
  sft4_title: 'Resuming sexual activity',
  sft4_text: 'No mandatory delay. Vaginal dryness is normal. Use lubricant. Communicate with your partner.',
  sft5_title: 'Warning signs ⚠️',
  sft5_text: 'Consult immediately if: fever >38°C, heavy bleeding, severe pain, sadness >2 weeks, dark thoughts, difficulty bonding with baby.',
  sft6_title: 'Baby blues vs Depression',
  sft6_text: 'Baby blues (D3-D10): normal, temporary. Postpartum depression (>2 weeks): deep sadness, loss of interest. Talk to a professional.',
  sft7_title: 'Breast engorgement',
  sft7_text: 'Common around D3-D5. Warm compresses before feeding, cold after. Shower massage. Feed frequently.',
  sft8_title: 'Perineal rehabilitation',
  sft8_text: 'Recommended after any delivery, from 6-8 weeks. Prevents incontinence and improves intimate comfort.',

  daily_title: 'How are you feeling?',
  daily_subtitle: 'Record your daily mood.',
  daily_mood: 'TODAY\'S MOOD',
  daily_exhausted: 'Exhausted',
  daily_sad: 'Sad',
  daily_neutral: 'Neutral',
  daily_good: 'Good',
  daily_great: 'Great',
  daily_stress: 'Stress level',
  daily_conjugal: 'Conjugal satisfaction',
  daily_intimate: 'Intimate satisfaction',
  daily_save: 'Save my tracking',
  daily_saved: 'Saved!',
  daily_evolution: 'Recent evolution',
  daily_satisfaction: 'Satisfaction',
  daily_stress_label: 'Stress',
  daily_history: 'Recent history',
  daily_no_entries: 'No entries. Start tracking above!',

  plan_title: 'Personal Plan',
  plan_subtitle: 'Exercises and advice adapted to your scores',
  plan_days: 'days',
  plan_focus: 'Priority areas',
  plan_focus_desc: 'Based on your scores, we recommend focusing on:',
  plan_activities: 'ACTIVITIES',
  plan_completed: 'activities completed',
  plan_psycho_focus: 'psychological well-being',
  plan_comm_focus: 'conjugal communication',
  plan_pp_focus: 'postpartum support',

  checkup_monthly: 'MONTHLY REPORT',
  checkup_global_score: 'Global Score',
  checkup_by_dimension: 'SCORES BY DIMENSION',
  checkup_evolution: 'Score evolution',
  checkup_recommendations: 'RECOMMENDATIONS',
  checkup_start_plan: 'Start a Personal Plan',
  checkup_see_results: 'View detailed results',
  checkup_trend_up: '↑ Rising',
  checkup_trend_down: '↓ Falling',
  checkup_trend_stable: '= Stable',
  checkup_trend_new: 'New',

  alerts_title: 'Alerts & Guidance',
  alerts_subtitle: 'Smart wellness monitoring',
  alerts_all_good: 'All good! ✨',
  alerts_none: 'No alerts at the moment. Keep up your regular tracking.',
  alerts_back_home: 'Back to home',
  alerts_important: 'Important reminder',
  alerts_disclaimer: 'NurtureFlow is a prevention and awareness tool. In case of distress, immediately contact a health professional or call 3114.',
  alerts_alert: 'alert',
  alerts_alerts: 'alerts',
  alerts_critical: 'critical',
  alerts_criticals: 'critical',
  alerts_warning: 'warning',
  alerts_warnings: 'warnings',

  admin_title: 'NurtureFlow Administration',
  admin_subtitle: 'Platform overview',
  admin_dashboard: 'DASHBOARD',
  admin_couples: 'Registered couples',
  admin_active: 'Active (7d)',
  admin_evals: 'Evaluations',
  admin_daily: 'Daily trackings',
  admin_avg_scores: 'Global Average Scores',
  admin_score_distrib: 'Score Distribution',
  admin_evals_by_type: 'Evaluations by Type',
  admin_recent_couples: 'RECENT COUPLES',
  admin_restricted: 'Restricted access',
  admin_restricted_msg: 'This section is reserved for the administrator.',
  admin_info: 'INFORMATION',
  admin_return: 'Return',

  nc_title: 'Create new couple',
  nc_subtitle: 'Register a couple in the database',
  nc_create: 'Create couple',
  nc_creating: 'Creating...',
  nc_success: 'Couple created successfully!',
  nc_created: 'Created!',

  misc_just_now: 'Just now',
  misc_ago_min: '{n} min ago',
  misc_ago_hours: '{n}h ago',
  misc_yesterday: 'Yesterday',
  misc_ago_days: '{n} days ago',
  misc_loading: 'Loading...',
  misc_error: 'Error',
  misc_back: 'Back',
  misc_min_read: 'min read',
  misc_period: 'Period',
  misc_back_library: 'Back to library',
  misc_video: 'Video',
  misc_guide: 'Guide',
  misc_article: 'Article',
}

};

// ── Translation function ──
function t(key, params = {}) {
  let text = translations[currentLang]?.[key] || translations.fr[key] || key;
  Object.entries(params).forEach(([k, v]) => {
    text = text.replace(`{${k}}`, v);
  });
  return text;
}

// ── Switch language ──
function switchLang(lang) {
  if (!LANGS[lang]) return;
  currentLang = lang;
  localStorage.setItem('nf_lang', lang);

  // Set direction
  const dir = LANGS[lang].dir;
  document.documentElement.setAttribute('dir', dir);
  document.documentElement.setAttribute('lang', lang);
  document.body.classList.toggle('rtl', dir === 'rtl');

  // Update all static i18n elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = t(key);
    } else {
      el.textContent = t(key);
    }
  });

  // Refresh current screen
  const screen = state.currentScreen;
  if (screen === 'auth') {
    if (state.authenticated) navigateTo('home');
    else showLogin();
  } else {
    navigateTo(screen);
  }
}

// ── Language Selector UI ──
function showLangSelector() {
  const overlay = document.createElement('div');
  overlay.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,0.4);z-index:200;display:flex;align-items:center;justify-content:center;animation:fadeIn 0.2s ease;';
  overlay.onclick = (e) => { if (e.target === overlay) overlay.remove(); };

  const modal = document.createElement('div');
  modal.style.cssText = 'background:var(--surface);border-radius:var(--radius-2xl);padding:var(--space-2xl);width:calc(100% - 40px);max-width:320px;box-shadow:var(--shadow-elevated);';
  modal.innerHTML = `
    <h3 style="font-size:18px;font-weight:600;margin-bottom:var(--space-xl);text-align:center;">
      <span class="material-symbols-outlined" style="vertical-align:middle;margin-right:8px;">translate</span>
      ${t('prof_lang')}
    </h3>
    ${Object.entries(LANGS).map(([code, info]) => `
      <button onclick="switchLang('${code}');this.closest('[style*=fixed]').remove();"
        style="width:100%;display:flex;align-items:center;gap:var(--space-lg);padding:var(--space-lg);border-radius:var(--radius-xl);margin-bottom:var(--space-sm);
        background:${currentLang===code?'var(--primary-fixed)':'var(--surface-container-low)'};
        border:2px solid ${currentLang===code?'var(--primary)':'transparent'};
        cursor:pointer;transition:all 0.15s;font-family:inherit;font-size:16px;">
        <span style="font-size:28px;">${info.flag}</span>
        <span style="font-weight:${currentLang===code?'700':'500'};color:${currentLang===code?'var(--primary)':'var(--on-surface)'};">${info.label}</span>
        ${currentLang===code?'<span class="material-symbols-outlined text-primary" style="margin-left:auto;">check_circle</span>':''}
      </button>
    `).join('')}
  `;
  overlay.appendChild(modal);
  document.body.appendChild(overlay);
}
